- buildout.cfg
- docs/source/_json/collection.json
- docs/source/_json/document.json
- docs/source/_json/event.json
- docs/source/_json/folder.json
- docs/source/_json/link.json
- docs/source/_json/newsitem.json
- src/plone/restapi/serializer.py
- src/plone/restapi/tests/test_documentation.py
When running tests, I end up with changed .json-files from the `test_documentation` test.
Maybe I was just doing it wrong, but I thought I'd fix what I can and try making the test run without having unnecessary changes.
My changes:
- Fix error when serializing python datetime object.
- Update `event.json` and `collection.json` with new fields.
- Always lowercase response-headers, since they were uppercase on my machine but commit in lowercase.
- Set timezone to `UTC` in `bin/test` (buildout) in order to have the same serialized dates wherever the machine runs.
Not sure if you want those changes, but I'd like to not have changed files when running the tests :wink:
> No changed files when running tests

- buildout.cfg
In order to solve the version conflict below we update the setuptools version.
```python
..
File "/home/travis/build/plone/plone.restapi/local/lib/python2.7/site-packages/zc/buildout/easy_install.py", line 605, in _maybe_add_setuptools
if ws.find(requirement) is None:
File "/home/travis/build/plone/plone.restapi/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 718, in find
raise VersionConflict(dist, req)
VersionConflict: (setuptools 18.5 (/home/travis/build/plone/plone.restapi/lib/python2.7/site-packages), Requirement.parse(setuptools==18.3.2))
The command "bin/buildout -N -t 3 -c travis.cfg" failed and exited with 1 during .
```
https://travis-ci.org/plone/plone.restapi/builds/89610721
> Fix travis tests: update setuptools version.

- src/plone/restapi/testing.py
- src/plone/restapi/tests/test_documentation.py
- src/plone/restapi/tests/test_error_handling.py
- src/plone/restapi/tests/test_services.py
Introduces a helper class `RelativeSession` that can be used to 
- Set up commonly used HTTP headers like `Accept: application/json` and `Authentication` *once* in the test setup
- Make requests using relative URLs. Avoids the need to always concatenate strings with `portal.absolute_url()`
This then allows to write tests like this
```python
response = self.api_session.get('non-existing-resource')
```
instead of
```python
response = requests.get(
self.portal_url + '/non-existing-resource',
headers={'Accept': 'application/json'},
auth=(SITE_OWNER_NAME, SITE_OWNER_PASSWORD)
)
```
which eliminates a ton of repetition and line noise, and makes the tests more expressive.
@tisto @jone @buchi
> Refactor tests: Introduce API session in functional tests

- buildout.cfg
Yet another setuptools version leading to a [travis build failure](https://travis-ci.org/plone/plone.restapi/builds/93390830). See #40
> Update setuptools version to fix travis build (yet again).

- buildout.cfg
The changes in https://github.com/plone/plone.dexterity/pull/34 are no longer needed.
The PR has already been closed. @tisto, @bloodbare I would suggest to also delete the branch plip-680.
> No longer use plone.dexterity from source (plip-680 branch).

- src/plone/restapi/tests/test_serializer_dexterity.py
Fixes the failing Plone 5 test by using `assertDictContainsSubset` instead of `assertDictEquals`.
We use `assertDictContainsSubset` in order not to have the Plone 5 tests fail because the automatic ID generation for the stock `Document` type works differently in Plone 5 than Plone 4.
A better solution for this (to get stable test behavior across Plone versions) is to create our own FTIs for tests instead of using the stock types from Plone (which may be named the same, but behave differently).
> Fix Plone 5 test by using assertDictContainsSubset

- src/plone/restapi/__init__.py
- src/plone/restapi/serializer/__init__.py
- src/plone/restapi/tests/test_serializer_dexterity.py
This removes an undeclared dependency on `plone.app.contenttypes` by making `ICollection` a conditional import.
[`test_serialize_to_json_collection`](https://github.com/plone/plone.restapi/blob/9dc3548077ddaf24ea52344ce1320343bfac9625/src/plone/restapi/tests/test_serializer.py#L174-L214) still passes, and including `plone.restapi` as dependency in a project without `plone.app.contenttypes` now also works.
Closes #51
/cc @tisto
> Remove undeclared dependency on p.a.contenttypes

- setup.py
These packages are not used anywhere.
> Remove dependencies on plone.validatehook and z3c.jbot.

- docs/source/_json/404_not_found.json
After plone/plone.rest#45 the response doesn't contain HTML any more.
> Update expected 404 response in JSON dump in docs:

- src/plone/restapi/interfaces.py
- src/plone/restapi/serializer/atcontent.py
- src/plone/restapi/serializer/collection.py
- src/plone/restapi/serializer/configure.zcml
- src/plone/restapi/serializer/converters.py
- src/plone/restapi/serializer/dxcontent.py
- src/plone/restapi/serializer/site.py
- src/plone/restapi/serializer/summary.py
- src/plone/restapi/tests/test_documentation.py
- src/plone/restapi/tests/test_dxfield_serializer.py
- src/plone/restapi/tests/test_serializer_converters.py
This **unifies** the implementation for producing **summary representations** of objects, and makes it **customizable** by introducing an `ISerializeToJsonSummary` adapter (adapts `context` and `request`).
In addition to unifying the implementation (which doesn't change the behavior, pure refactoring), I also used the summary representation for serializing relation values - this means their representation now also includes `title` and `description` instead of just the URL.
The `ISerializeToJsonSummary` adapter is used to create representations in the following places:
- Children of the Plone site root
- Children of folderish AT objects
- Children of folderish DX objects
- Parent of AT objects
- Parent of DX objects
- Members of collections
- Relation values
Once search is implemented, …
> Make summary representations customizable

- docs/source/_json/collection.json
- docs/source/_json/document.json
- docs/source/_json/event.json
- docs/source/_json/file.json
- docs/source/_json/folder.json
- docs/source/_json/image.json
- docs/source/_json/link.json
- docs/source/_json/newsitem.json
- docs/source/_json/search.json
- docs/source/_json/siteroot.json
- src/plone/restapi/serializer/summary.py
- src/plone/restapi/tests/test_atcontent_serializer.py
- src/plone/restapi/tests/test_dxfield_serializer.py
- src/plone/restapi/tests/test_serializer.py
- src/plone/restapi/tests/test_serializer_catalog.py
- src/plone/restapi/tests/test_serializer_converters.py
- src/plone/restapi/tests/test_serializer_summary.py
This adds the object's `portal_type` to its summary representation, as discussed in #76.
Also includes:
- some more specific tests for summary serializers that cover all the types of objects we're currently producing summaries of
- a small bugfix: Making sure we always return JSON compatible data from summary serializers
```json
{
"@id": "http://localhost:55001/plone/front-page",
"description": "Congratulations! You have successfully installed Plone.",
"title": "Welcome to Plone"
}
```
=>
```json
{
"@id": "http://localhost:55001/plone/front-page",
"@type": "Document",
"description": "Congratulations! You have successfully installed Plone.",
"title": "Welcome to Plone"
}
```
Closes #76
> Add portal_type to summary representations

- base.cfg
- src/plone/restapi/services/__init__.py
- src/plone/restapi/services/content/add.py
- src/plone/restapi/services/content/delete.py
- src/plone/restapi/services/content/get.py
- src/plone/restapi/services/content/update.py
- src/plone/restapi/services/registry/get.py
- src/plone/restapi/services/registry/update.py
- src/plone/restapi/services/search/get.py
- src/plone/restapi/services/types/get.py
- src/plone/restapi/services/workflow/info.py
- src/plone/restapi/services/workflow/transition.py
- src/plone/restapi/tests/test_workflow.py
Implements a base class for all services defined in plone.restapi that basically renders the results to JSON. This functionality has been removed in plone.rest (https://github.com/plone/plone.rest/pull/52) an now needs to be done in plone.restapi.
Services now have to implement the `reply()` method to process the request. This method should return a JSON serializable data structure or the no content marker.
> Service base class

- docs/source/_json/collection.json
- docs/source/_json/document.json
- docs/source/_json/event.json
- docs/source/_json/file.json
- docs/source/_json/folder.json
- docs/source/_json/image.json
- docs/source/_json/link.json
- docs/source/_json/newsitem.json
- src/plone/restapi/profiles/testing/workflows.xml
- src/plone/restapi/serializer/atcontent.py
- src/plone/restapi/serializer/dxcontent.py
- src/plone/restapi/tests/test_atcontent_serializer.py
- src/plone/restapi/tests/test_dxcontent_serializer.py
Includes the workflow state in the `review_state` attribute in content serializations.
> Add review_state to content serializations

- docs/source/_json/collection.json
- docs/source/_json/folder.json
- docs/source/_json/search.json
- docs/source/_json/siteroot.json
- docs/source/introduction.rst
- src/plone/restapi/serializer/atcontent.py
- src/plone/restapi/serializer/catalog.py
- src/plone/restapi/serializer/collection.py
- src/plone/restapi/serializer/dxcontent.py
- src/plone/restapi/serializer/site.py
- src/plone/restapi/tests/helpers.py
- src/plone/restapi/tests/test_atcontent_serializer.py
- src/plone/restapi/tests/test_search.py
- src/plone/restapi/tests/test_serializer.py
- src/plone/restapi/tests/test_serializer_catalog.py
The `member` attribute on collection-like resources was an artifact from the Hydra `Collection` type. We're only loosely following Hydra at this point, so we're choosing to name it somewhat more sensibly.
> Rename 'member' attribute to 'items' for collection-like resources

- docs/source/_json/login.json
- docs/source/_json/login_renew.json
- docs/source/_json/logout.json
- docs/source/authentication.rst
- setup.py
- src/plone/restapi/__init__.py
- src/plone/restapi/configure.zcml
- src/plone/restapi/pas/add_plugin.zpt
- src/plone/restapi/pas/config.zpt
- src/plone/restapi/pas/plugin.py
- src/plone/restapi/services/auth/configure.zcml
- src/plone/restapi/services/auth/login.py
- src/plone/restapi/services/auth/logout.py
- src/plone/restapi/services/auth/refresh.py
- src/plone/restapi/services/auth/renew.py
- src/plone/restapi/services/configure.zcml
- src/plone/restapi/setuphandlers.py
- src/plone/restapi/tests/test_auth.py
- src/plone/restapi/tests/test_documentation.py
- src/plone/restapi/tests/test_pas.py
Provides a PAS plugin for JWT based authentication.
Provides endpoints `/@login`, `/@logout` and `/@login-renew`
> Authentication

- docs/source/_json/batching.json
- docs/source/_json/collection.json
- docs/source/_json/folder.json
- docs/source/_json/search.json
- docs/source/_json/siteroot.json
- docs/source/batching.rst
- docs/source/crud.rst
- docs/source/index.rst
- docs/source/plone-content.rst
- docs/source/searching.rst
- src/plone/restapi/batching.py
- src/plone/restapi/search/handler.py
- src/plone/restapi/search/query.py
- src/plone/restapi/serializer/atcontent.py
- src/plone/restapi/serializer/catalog.py
- src/plone/restapi/serializer/collection.py
- src/plone/restapi/serializer/configure.zcml
- src/plone/restapi/serializer/dxcontent.py
- src/plone/restapi/serializer/site.py
- src/plone/restapi/tests/test_batching.py
- src/plone/restapi/tests/test_documentation.py
- src/plone/restapi/tests/test_search.py
- src/plone/restapi/tests/test_serializer.py
- src/plone/restapi/tests/test_serializer_catalog.py
Implements batching for
- Plone Site Root children
- Dexterity Folder
- Archetypes Folders
- Collections
- Search Results
Also changes implementation for `GET` on folderish contexts so catalog queries are used instead of `objectValues()`.
TODO:
Closes #8
> Implement Batching

- setup.py
- src/plone/restapi/serializer/atcollection.py
- src/plone/restapi/serializer/atfields.py
- src/plone/restapi/serializer/configure.zcml
- src/plone/restapi/testing.py
- src/plone/restapi/tests/attypes.py
- src/plone/restapi/tests/test_atcollection.py
- src/plone/restapi/tests/test_atfield_deserializer.py
- src/plone/restapi/tests/test_atfield_serializer.py
Archetypes based plone.app.collection serializer was missing and thus the QueryField serializer for Archetypes too.
> Serializers for Archetypes new style collections

- docs/source/_json/search.json
- docs/source/_json/siteroot.json
- plone-4.3.x.cfg
- plone-5.0.x.cfg
- src/plone/restapi/testing.py
- src/plone/restapi/tests/test_batching.py
- Update test setup to use Plone 5.0.4 and Plone 4.3.9 without downpinning p.a.contenttypes
- Create `SITE_OWNER_NAME` user in test layer (was previously done in p.a.contenttypes)
- Grant `Manager` role to `TEST_USER_ID` (was previously done in p.a.contenttypes)
> Use latest Plone versions in tests

- src/plone/restapi/batching.py
- src/plone/restapi/search/handler.py
- src/plone/restapi/serializer/atcollection.py
- src/plone/restapi/serializer/atcontent.py
- src/plone/restapi/serializer/catalog.py
- src/plone/restapi/serializer/collection.py
- src/plone/restapi/serializer/configure.zcml
- src/plone/restapi/serializer/dxcontent.py
- src/plone/restapi/serializer/site.py
- src/plone/restapi/tests/test_batching.py
- src/plone/restapi/tests/test_serializer_catalog.py
The `LazyCatalogResultSerializer` has been removed in #99 without a pressing need to do so ([see here](https://github.com/plone/plone.restapi/commit/d5e84ca1cfb52187ef33c975a4a7929e3c2edcf2#commitcomment-17748938)). Therefore we reintroduce it here and make it handle the batching logic that was previously left to the `SearchHandler`.
@tisto @sneridagh
> Reintroduce LazyCatalogResultSerializer with batching logic

- src/plone/restapi/imaging.py
- src/plone/restapi/tests/test_atfield_serializer.py
- src/plone/restapi/tests/test_dxfield_serializer.py
This fixes scale URLs for image field serialization.
The field name was [hardcoded as `image` in `get_scales()`](https://github.com/plone/plone.restapi/blob/275ff821aa44f2f6da869f74788e181251ea82ed/src/plone/restapi/imaging.py#L25), which is why the results were correct for the Plone stock image content type, but incorrect for custom types with image fields with different field names.
Fixes #123
> Make sure image scale URLs contain the actual field name.

- CHANGES.rst
- docs/source/_json/workflow_get.json
- docs/source/_json/workflow_post.json
- setup.py
- src/plone/restapi/tests/test_documentation.py
Use [`freezegun`](https://github.com/spulec/freezegun) to freeze hard to control timestamps in response dumps used for documentation.
This really just addresses the constantly changing timestamps in the `@workflow` response dumps. I considered rewriting all the other places where we set creation / modification dates manually, but I don't think it currently adds any value - so I suggest to just use `freezegun` to target the timestamps that would otherwise be hard to control.
@tisto
Closes #133
> Tests: Use `freezegun` to freeze hard to control timestamps

- docs/source/_json/types_document.json
The JSON dump in `types_document.json` is out of sync with the current implementation since merging #131.
As far as I can tell, what happened here is
- `required` (on the field level) was introduced in #129 (9384a5a0)
- reverted in #130 (5820fce6)
- and #131 wasn't up-to-date with `master` when producing and checking in the output from `bin/test -t test_documentation`
*(No changelog entry on purpose, because this changeset should have been part of commits that are already merged)* 
@tisto @ebrehault
> Update types_document.json to be up-to-date with current implementation.

- .travis.yml
- CHANGES.rst
- base.cfg
- docs/source/_json/types_document.json
- test-no-uncommitted-doc-changes.in
⚠️  Based on #138 to not have tests for this one fail, merge that one first ⚠️ 
This adds a CI test that will fail if there are uncommitted changes (dirty working dir) to any of the files in `docs/source/_json` after running the tests from `test_documentation.py`.
The purpose of this is to stop having the dynamically produced request/response dumps that are included in the docs get out of sync with the actual implementation. This addresses one of the points mentioned in #137.
Implementation:
- A new script `bin/test-no-uncommitted-doc-changes` that fails if there are modified files in `docs/source/_json`, and provides a message including the diff of changed files
- An entry in `.travis.yml` that calls this script *after* `bin/test` has been run
- A condition in …
> Fail tests on uncommitted changes to docs/source/_json/

- CHANGES.rst
- docs/source/authentication.rst
Fixed parameter "data" to JSON format
Before commit:
In [137]: requests.post('http://localhost:8080/Plone/@login',
.....:               headers={'Accept': 'application/json', 'Content-Type': 'application/json'},
.....:               data={'login': 'admin', 'password': 'admin'})
Out[137]: <Response [500]>
2016-08-10 15:41:06 ERROR Zope.SiteErrorLog 1470854466.590.500058837151 http://localhost:8080/Plone/@login
Traceback (innermost last):
Module ZPublisher.Publish, line 138, in publish
Module ZPublisher.mapply, line 77, in mapply
Module ZPublisher.Publish, line 48, in call_object
Module plone.rest.service, line 20, in __call__
Module plone.restapi.services, line 15, in render
Module plone.restapi.services.auth.login, line 16, in reply
Module plone.restapi.deserializer, line 11, in json_body …
> Fixed parameter 'data' to JSON format

- CHANGES.rst
- src/plone/restapi/services/auth/login.py
- src/plone/restapi/services/auth/renew.py
This disables automatic CSRF protection for the `@login` and `@login-renew` endpoints.
If persisting tokens server-side ("Store Tokens" option on the `jwt_auth` Plugin) is enabled, those requests need to be allowed to cause DB writes, otherwise the transaction might be aborted by `plone.protect`.
**Steps to reproduce**:
- Use `plone.protect` >= 3.0 (and `plone4.csrffixes` if on Plone 4.3)
- Create a fresh Plone Site and install the `plone.restapi:default` profile
- Enable "Store Tokens" in the `acl_users/jwt_auth` Plugin
- Do a `POST` to `@login` while already authenticated (`plone.protect` doesn't (need to) protect requests from Anonymous users)
**Security Considerations**
I've chosen to blanket whitelist those requests using the `IDisableCSRFProtection` request interface. Ideally, it …
> Disable automatic CSRF protection for @login and @login-renew endpoints

- CHANGES.rst
- src/plone/restapi/pas/plugin.py
An unchecked `<input type="checkbox" />` will be omitted entirely from the request if unchecked - so an approach like `bool(REQUEST.form.get('field', True))` will end up always being `True`.
@tisto
> Fix bug where disabling the "Use Keyring" flag wasn't persisted in jwt_auth plugin

- CHANGES.rst
- docs/source/authentication.rst
- src/plone/restapi/configure.zcml
- src/plone/restapi/permissions.py
- src/plone/restapi/permissions.zcml
- src/plone/restapi/profiles/default/metadata.xml
- src/plone/restapi/profiles/default/rolemap.xml
- src/plone/restapi/services/__init__.py
- src/plone/restapi/tests/test_permissions.py
- src/plone/restapi/upgrades/configure.zcml
- src/plone/restapi/upgrades/profiles/0002/rolemap.xml
- src/plone/restapi/upgrades/to0002.py
This will introduce a **dedicated permission to use the REST API**:
The permission `plone.restapi: Use REST API` will be required to use the REST API at all, in addition to any service-specific permissions that are required.
This permission will be granted to `Anonymous` (i.e. everybody) by default via `rolemap.xml`. This allows to restrict API access to certain roles, e.g. in order to only allow API access to service users and/or Managers.
@tisto @buchi
/cc @vangheem
> Introduce dedicated permission to use REST API

- docs/source/index.rst
Remove duplicate reference to `'types.rst'` from ToC.
(See screenshot for what the current issue is).
> Docs: Remove duplicate reference to 'types.rst' from ToC.

- docs/source/crud.rst
1) Use `json=` for requests library.
-> `data=` sends multipart/form-data encoded data
-> `params=` sends params as URL params
->  `json=` encodes the dict as json and sends that as payload
That means for non-GET-requests we usually want `json=`, for GET-requests we want `params=` (e.g. for search filters).
2) Sync `POST` and `PATCH` examples:
Make sure that the `http-request`, `curl`, `httpie` and `python-requests`  examples send the same data in the examples.
I have not changed `PUT`, although it is not in sync, because it is not yet implemented and I do not know which example is the correct one.
---
Is a changelog required for such changes? It does not change any behavior.
> Crud Documentation: Update examples

- CHANGES.rst
- src/plone/restapi/serializer/atcontent.py
- src/plone/restapi/serializer/dxcontent.py
- src/plone/restapi/tests/test_atcontent_serializer.py
- src/plone/restapi/tests/test_serializer.py
Fixes the `sort_on` parameter in serializer queries to ensure container items are always ordered by `getObjectPositionInParent`.
Includes regression tests for **AT folders** and **DX folders** (whose queries were incorrect) as well as the **Plone Site** (which was fine).
Closes #182
> Fix queries to ensure ordering of container items by getObjectPositionInParent

- src/plone/restapi/tests/test_types.py
Expected value comes first in assertions, be as explicit as possible, one empty line between precondition and assertions.
> Improve types endpoint tests.

- CHANGES.rst
- docs/source/_json/types_document.json
- src/plone/restapi/tests/test_types.py
- src/plone/restapi/types/adapters.py
- src/plone/restapi/types/utils.py
This new implementation instantiates a minimal `z3c.form` in order to allow `plone.autoform` to do all the heavy lifting (particularly processing fields, fieldset directives and field move directives).
This makes sure we correctly process and respect (or at least have the option to respect):
- Schema interface inheritance (IRO)
- Additional schemata from behaviors
- `plone.autoform` directives / form hints:
- Fieldsets
- Field moves
- Omitted fields
- Field modes
- Field level permissions
Basically all the heavy lifting is done in (or triggered from) [`plone.autoform.base.AutoFields. updateFieldsFromSchemata()`](https://github.com/plone/plone.autoform/blob/1b24ddfa8cf6e68914772d5d1c5fe89653c7a7c3/plone/autoform/base.py#L34-L135)
So instead of attempting to do these complex tasks ourselves …
> Overhaul JSON schema generation for @types endpoint

- CHANGES.rst
- src/plone/restapi/search/handler.py
- src/plone/restapi/tests/test_search.py
`@search` endpoint: Also prefill `path` query dict with context path.
This will allow users to supply an argument like `path.depth=1`, and still have `path.query` be prefilled server-side to the context's path.
@sneridagh
> @search endpoint: Also prefill path query dict with context path.

- CHANGES.rst
- docs/source/_json/batching.json
- docs/source/_json/collection.json
- docs/source/_json/folder.json
- docs/source/_json/search.json
- docs/source/_json/siteroot.json
- src/plone/restapi/serializer/summary.py
- src/plone/restapi/testing.py
- src/plone/restapi/tests/test_atcollection.py
- src/plone/restapi/tests/test_atcontent_serializer.py
- src/plone/restapi/tests/test_dxfield_serializer.py
- src/plone/restapi/tests/test_serializer.py
- src/plone/restapi/tests/test_serializer_catalog.py
- src/plone/restapi/tests/test_serializer_converters.py
- src/plone/restapi/tests/test_serializer_summary.py
Since this is already provided by IContentListingObject, we can easily add it to the summary serializer at no cost. By doing this, it will be easier to build basic listings from the summary of a folder.
Maybe there's still some other IContentListingObject information that we could include...
https://github.com/plone/plone.app.contentlisting/blob/master/plone/app/contentlisting/interfaces.py#L10
Bottom line is that I had to amend 17 tests failures! ;)
What do you think? /cc @lukasgraf @buchi @tisto @bloodbare
> Add review_state on summary serializer

- CHANGES.rst
- src/plone/restapi/types/adapters.py
- src/plone/restapi/types/configure.zcml
- src/plone/restapi/types/utils.py
This allows us to prevent rending choices for relatedItems, which would dump the whole DB.
Fixes #199 by not rendering relatedItems' choices.
> Add support for named IJsonSchemaProvider adapter to target a single field in a schema

- CHANGES.rst
- docs/source/_json/sharing_folder_get.req
- docs/source/_json/sharing_folder_get.resp
- docs/source/_json/sharing_folder_post.req
- docs/source/_json/sharing_folder_post.resp
- docs/source/sharing.rst
- src/plone/restapi/serializer/local_roles.py
- src/plone/restapi/tests/test_content_local_roles.py
- src/plone/restapi/tests/test_documentation.py
It's required to build an UI on the top of the sharing feature.
> Add available_roles attribute to the GET @sharing endpoint.

- docs/source/_json/vocabularies.resp
- plone-4.3.x.cfg
- plone-5.0.x.cfg
Plone 4.3.x setup can't be updated to 4.3.12 because some errors on the generated KGS, so I updated it to Plone 4.3.11 (see https://community.plone.org/t/plone-4-3-12-soft-released/3529/14)
> Update testing environment to latest Plone 4 and 5 releases

- CHANGES.rst
- src/plone/restapi/deserializer/local_roles.py
I propose to make the import of `LocalrolesModifiedEvent` from `plone.app.workflow` conditional, so `plone.restapi` doesn't prevent Plone 4.3 deployments < 4.3.4 from booting.
---
A deployment with `plone.restapi == 1.0a10` and Plone < 4.3.4 will currently fail to boot because of the import of `LocalrolesModifiedEvent` from `plone.app.workflow`. This event has only been [added in `p.a.workflow` 2.2.1](https://github.com/plone/plone.app.workflow/pull/5), resp. backported to 2.1.8, which is available in Plone 4.3.4 or higher.
This currently bites us, preventing us from using the most recent `plone.restapi`, because we still have a few deployments that we can't yet bump to the most recent 4.3.x version.
I'm definitely not advocating here that we should officially claim support for older …
> Make import of LocalrolesModifiedEvent conditional

- CHANGES.rst
- setup.py
This dependency is gone in Plone 5.1.
> Add Products.PasswortResetTool to dependencies.

- src/plone/restapi/services/copymove/copymove.py
- src/plone/restapi/services/principals/get.py
- src/plone/restapi/tests/test_copymove.py
- src/plone/restapi/types/adapters.py
- src/plone/restapi/types/configure.zcml
- src/plone/restapi/types/z3crelationadapter.py
Fixes #288.
This PR removes the use of plone.api and zope.intid, and makes the use of z3c.relationfield conditional on the installation of it (present in Plone 5, not in Plone 4.3.x)
See #289 for further discussion.
Merge only this one or #289, but not both.
> Fix plone.api, z3c.relationfield and zope.intid dependencies.

- CHANGES.rst
- docs/source/_json/groups_created.req
- docs/source/_json/groups_created.resp
- docs/source/_json/groups_get.resp
- docs/source/_json/groups_update.req
- docs/source/groups.rst
- src/plone/restapi/serializer/configure.zcml
- src/plone/restapi/serializer/group.py
- src/plone/restapi/serializer/user.py
- src/plone/restapi/services/groups/add.py
- src/plone/restapi/services/groups/get.py
- src/plone/restapi/services/groups/update.py
- src/plone/restapi/services/principals/get.py
- src/plone/restapi/tests/test_documentation.py
- src/plone/restapi/tests/test_serializer_group.py
- src/plone/restapi/tests/test_services_groups.py
Support adding and removing group members in the add and patch of the `@groups` endpoint.
Group membership is retrievable in the get of a group on the `@groups/[group id]` endpoint as the subobject 'users'.
> Group membership add/remove

- CHANGES.rst
- docs/source/batching.rst
Fixes the example response / request in the [batching docs](http://plonerestapi.readthedocs.io/en/latest/batching.html#parameters).
I broke those in 32227e74 by accidentally replacing the request/response included in the docs with the one from the `@types` endpoint.
Fixes #349
> Docs: Fix batching example request/response.

- CHANGES.rst
- src/plone/restapi/services/configure.zcml
The service registrations in [`plone/restapi/services`](https://github.com/plone/plone.restapi/tree/master/src/plone/restapi/services) use permissions that are defined in `Products.CMFCore`'s `permissions.zcml`.
In many cases, `permissions.zcml` has already been loaded by another package, but depending on the exact ZCML load order that happens to play out it may not, causing a `ComponentLookupError`.
The top level ZCML in the `service` package should therefore **explicitly load** `permissions.zcml`. 
Fixes #395
> Fix ZCML load order issue by explicitly loading permissions.zcml from CMFCore

- base.cfg
- src/plone/restapi/services/content/get.py
- src/plone/restapi/services/workflow/info.py
- src/plone/restapi/tests/test_tus.py
- versions.cfg
We did not use bracket indentation consistently so far. This check makes sure we do.
> Add Flake8 config with check for bracket indentation.

- CHANGES.rst
- docs/source/_json/translations_delete.req
- docs/source/_json/translations_delete.resp
- docs/source/_json/translations_get.req
- docs/source/_json/translations_get.resp
- docs/source/_json/translations_post.req
- docs/source/_json/translations_post.resp
- docs/source/index.rst
- docs/source/translations.rst
- src/plone/restapi/services/configure.zcml
- src/plone/restapi/services/multilingual/configure.zcml
- src/plone/restapi/services/multilingual/pam.py
- src/plone/restapi/testing.py
- src/plone/restapi/tests/test_documentation.py
- src/plone/restapi/tests/test_translations.py
See https://github.com/plone/plone.restapi/issues/225#issuecomment-298526226 for rational behind this.
> Add translation endpoint

- CHANGES.rst
- setup.py
- src/plone/restapi/deserializer/dxfields.py
- src/plone/restapi/tests/dxtypes.py
- src/plone/restapi/tests/test_dxfield_deserializer.py
> Fix datetime deserialization for timezone aware fields

- CHANGES.rst
- docs/source/_json/jwt_logged_in.req
- docs/source/_json/jwt_login.resp
- docs/source/_json/jwt_login_renew.req
- docs/source/_json/jwt_login_renew.resp
- docs/source/_json/jwt_logout.req
- src/plone/restapi/pas/plugin.py
- src/plone/restapi/profiles/default/metadata.xml
- src/plone/restapi/services/auth/login.py
- src/plone/restapi/setuphandlers.py
- src/plone/restapi/tests/test_auth.py
- src/plone/restapi/upgrades/configure.zcml
- src/plone/restapi/upgrades/to0003.py
Another approach to fix #178, #127, #168 
Obsoletes #378 
- The `@login` endpoints now checks for an installed JWT plugin in the acl_users folder where the logging in user has been found.
- The JWT plugin is also installed in the Zope root acl_users folder.
- Each JWT plugin uses a unique signing secret to prevent authenticating tokens issued by other JWT plugins.
> Fix handling of Zope root users

- CHANGES.rst
- src/plone/restapi/interfaces.py
- src/plone/restapi/serializer/configure.zcml
- src/plone/restapi/serializer/converters.py
- src/plone/restapi/serializer/dxfields.py
- src/plone/restapi/tests/test_dxcontent_serializer.py
- src/plone/restapi/tests/test_serializer_converters.py
Fixes #424
This changes the serialisers to pass in the correct context.
> Pass context to richtext.output_relative_to

- CHANGES.rst
- src/plone/restapi/deserializer/dxcontent.py
- src/plone/restapi/tests/test_dxcontent_deserializer.py
With this event handlers can lookup which fields were modified. It mimics the same behavior as in z3c.form.
> Include descriptions of modified fields in object-modified event

- .gitignore
- CHANGES.rst
- src/plone/restapi/pas/plugin.py
- src/plone/restapi/tests/test_pas.py
> Ensure the userid returned by `authenticateCredentials` is a byte string.

- CHANGES.rst
- docs/source/content.rst
- src/plone/restapi/deserializer/__init__.py
- src/plone/restapi/serializer/atcontent.py
- src/plone/restapi/serializer/dxcontent.py
- src/plone/restapi/tests/test_boolean_value.py
- src/plone/restapi/tests/test_content_get.py
This allow to get only the content without its children. It avoids a catalog query when not needed.
I didn't find test for testing the content GET, did I miss them?
> Add `include_items` option to `SerializeFolderToJson`.

- CHANGES.rst
- docs/source/_json/workflow_post.resp
- src/plone/restapi/services/workflow/info.py
- src/plone/restapi/services/workflow/transition.py
- src/plone/restapi/testing.py
- src/plone/restapi/tests/test_workflow.py
I added a workflow in the testing profile (`test_workflow`) which is the `simple_publication_workflow` but with a unicode character in every title. I set it as the workflow for the custom testing types.
> Fix workflow translations with unicode characters

- .travis.yml
See: https://github.com/travis-ci/docs-travis-ci-com/issues/1540
Brought to my attention by this PR: https://github.com/collective/icalendar/pull/249
> Quote version strings in YAML

- CHANGES.rst
- docs/source/content.rst
- src/plone/restapi/deserializer/dxcontent.py
- src/plone/restapi/tests/dxtypes.py
- src/plone/restapi/tests/test_content_patch.py
- src/plone/restapi/tests/test_dxcontent_deserializer.py
> Support null in content PATCH to delete a field value #187

- CHANGES.rst
- docs/source/_json/translations_get.resp
- docs/source/expansion.rst
- docs/source/translations.rst
- docs/source/upgrade-guide.rst
- src/plone/restapi/services/multilingual/configure.zcml
- src/plone/restapi/services/multilingual/pam.py
- src/plone/restapi/tests/test_expansion.py
- src/plone/restapi/tests/test_translations.py
- Make `@translations` endpoint expandable
- Modify `@translations` endpoint to return results in an attribute called `items` instead of `translations` as previously to behave like the other expandable endpoints.
- Document the upgrade path from the previous version
> Expandable translations

- CHANGES.rst
- src/plone/restapi/search/handler.py
- src/plone/restapi/tests/test_search.py
Solves issue #186 
If called via VHM it will include the VirtualHostRoot path in a path search
> Add VHM support to @search

- CHANGES.rst
- setup.py
- src/plone/restapi/deserializer/dxfields.py
- src/plone/restapi/serializer/converters.py
- src/plone/restapi/testing.py
- src/plone/restapi/tests/test_serializer_converters.py
Most of the test failures for Plone 5.2 were related to missing initialization of ZServer, which is fixed but not yet merged here: https://github.com/plone/plone.testing/pull/45
Other Plone 5.2 failures were related to date/timezone related offsets which did not match (I do not yet understand why this failures only were apparent for Plone 5.2).
Investigating this, I found out that the date/times were not consistently converted to UTC when exporting. I recall some discussions about this including some contradictory statements including from myself in https://github.com/plone/plone.restapi/issues/253
However, I think since ISO8601 lacks of a concept of timezone names which are necessary to do date math when daylight saving time boundaries are included (timezone offsets do not allow to …
> convert date/times to UTC when exporting, use python-datetime for parsing date strings

- CHANGES.rst
- src/plone/restapi/setuphandlers.py
- versions.cfg
Fixes issue #532.
I had to pin plone.recipe.zope2instance to newer 4.4.0, so buildout would finish locally.
> Hide upgrade profile from add-ons control panel in 5.1

- CHANGES.rst
- docs/source/_json/roles.resp
- docs/source/roles.rst
- src/plone/restapi/services/roles/get.py
- src/plone/restapi/testing.py
- src/plone/restapi/tests/test_roles.py
Include translated role title in `@roles` GET:
This returns the translated role name (**as displayed in the "Users and Groups" control panel**) as the title property in the output of the `@roles` endpoint.
Also includes some groundwork in setting up languages (available & supported, request negotiation) consistently during tests.
/cc @erral 
---
Note that the sharing view uses a different set of translations for the same role ID. At first, my intent was to use the same serialization of roles (plus their titles) for both the `@roles` endpoint as well as well as the available roles in the `@sharing` endpoint.
But since Plone itself uses different translations for roles in two places, I would suggest to just handle them seperately in these endpoints as well:
*Examples for how role titles are …
> Include translated role title in `@roles` GET

- src/plone/restapi/testing.py
- src/plone/restapi/tests/test_atcontent_serializer.py
- src/plone/restapi/tests/test_documentation.py
- src/plone/restapi/tests/test_dxcontent_serializer.py
- src/plone/restapi/tests/test_expansion.py
- src/plone/restapi/tests/test_services_vocabularies.py
Fixes https://github.com/plone/plone.restapi/issues/470
The issue was the generation of new transaction ids in ZODB.utils.newTid.
For the documentation test only we patch the newTid to use the unpatched time and gmtime methods, in a new testing layer.
> Fix test_documentation (ReadConflictError)

- CHANGES.rst
- src/plone/restapi/services/types/get.py
- src/plone/restapi/tests/test_services_types.py
> Translate the fti title in @types endpoint

- CHANGES.rst
- src/plone/restapi/deserializer/dxfields.py
- src/plone/restapi/tests/test_dxfield_deserializer.py
Make sure DX `DefaultFieldDeserializer` validates field values.
> Make sure DX DefaultFieldDeserializer validates field values.

- .travis.yml
- base.cfg
- docs/source/glossary.rst
- docs/source/index.rst
- docs/source/roles.rst
- docs/source/sharing.rst
- test-no-sphinx-warnings.in
Adds a **test that fails if Sphinx build has warnings or errors.**
*(Changelog entry omitted on purpose since it's not a user-visible bugfix/feature)* 
This is so we can keep documentation at a high quality level, and avoid piling up too many warnings. Especially frustrating is documentation that has been carefully written, but never got published because it wasn't included in a toctree.
The test is a simple bash script that checks the output and return code of `bin/sphinxbuild` and errors out to fail the build if either
- `bin/sphinxbuild` exited with return code 1 (hard errors)
- the output contains WARNINGs
In addition, I fixed all the existing Sphinx warnings.
The build failure is displayed in a way on travis where it should be immediately visible to developers / first time …
> Have tests fail on Sphinx documentation errors / warnings

- CHANGES.rst
- src/plone/restapi/deserializer/atcontent.py
- src/plone/restapi/tests/test_content_patch.py
> Reindex AT content on PATCH

- CHANGES.rst
- src/plone/restapi/services/users/update.py
After the change of MemberData to MemberAdapter, there is no longer a method userSetPassword of the user instance. Using the same approach as the PasswordResetTool.
> Fix change password on Plone 5.2.

- CHANGES.rst
- docs/source/_json/sharing_folder_get.resp
- docs/source/_json/sharing_folder_get_include_titles.req
- docs/source/_json/sharing_folder_post.req
- docs/source/_json/sharing_search.resp
- docs/source/sharing.rst
- docs/source/upgrade-guide.rst
- src/plone/restapi/serializer/local_roles.py
- src/plone/restapi/services/content/sharing.py
- src/plone/restapi/tests/test_content_local_roles.py
- src/plone/restapi/tests/test_documentation.py
⚠️ breaking change - planned for 3.0.0 ⚠️ 
---
This will include translated role titles in the `available_roles` property of a `@sharing` GET response.
This is a breaking change, since the `available_roles` property will now, instead of a flat list of strings, contain a list of dicts with role IDs and their translated titles.
---
For reference, this is how role titles are currently being displayed / translated in Plone 5:
> Include translated role titles in `@sharing` GET

- CHANGES.rst
- docs/source/upgrade-guide.rst
- src/plone/restapi/deserializer/atcontent.py
- src/plone/restapi/deserializer/dxcontent.py
- src/plone/restapi/services/content/add.py
- src/plone/restapi/services/content/tus.py
- src/plone/restapi/services/content/utils.py
- src/plone/restapi/tests/test_atcontent_deserializer.py
- src/plone/restapi/tests/test_content_patch.py
- src/plone/restapi/tests/test_content_post.py
- src/plone/restapi/tests/test_content_utils.py
This makes object creation in plone.restapi behave more like TTW object creation.
New objects are now created in the following way:
1. Create an empty object
2. Deserialize it
3. Fire object created event
4. Add object to container
5. Fire object added and container modified events
Before that change new objects were created in the this way:
1. Create an empty object
2. Fire object created event
3. Add object to container
4. Fire object added and container modified events
5. Deserialize object
6. Fire modified event
> Fix object creation events

- CHANGES.rst
- setup.py
- src/plone/restapi/tests/test_documentation.py
Make sure to include HTTP examples in the **installed egg**, so `test_documentation` tests also work against an installed release of `plone.restapi`.
We need to do this dynamically because the `data_files` argument to `setup()` doesn't support globs (wildcards).
The examples need to be included [via `data_files`](https://docs.python.org/3/distutils/setupscript.html#installing-additional-files) because they are outside a Python package. So we can't include them using `package_data`, which [only works relative to Python packages](https://docs.python.org/3/distutils/setupscript.html#installing-package-data). (The `MANIFEST` only controls what gets included in the *source distribution*. Listing these files in `data_files` ensures they actually get *copied to the installed `.egg`*).
If the …
> Properly include HTTP examples in installed egg

- .travis.yml
- base.cfg
limit urls used for downloading (just like coredev) - can speed up buildout runs
> [WIP] optimize buildout speed + travis buildout cache

- CHANGES.rst
- src/plone/restapi/tests/dxtypes.py
Fixes ``test_search`` to work with bug fixed ``plone.indexer``.
This fixes #579.
Refers to https://github.com/plone/Products.CMFPlone/issues/2469
> fixes #579

- CHANGES.rst
- docs/source/searching.rst
- src/plone/restapi/search/handler.py
- src/plone/restapi/tests/http-examples/search_multiple_paths.req
- src/plone/restapi/tests/http-examples/search_multiple_paths.resp
- src/plone/restapi/tests/test_documentation.py
- src/plone/restapi/tests/test_search.py
PLEASE MERGE THIS FIRST:
https://github.com/plone/plone.restapi/pull/613
(and then I'll do a rebase before we merge this one)
Fix AttributeError: 'list' object has no attribute 'lstrip' in a virtual hosting setting when restricting search to multiple paths (path.query is a list).
> Fix AttributeError in a virtual hosting setting when restricting search to multiple paths

- src/plone/restapi/tests/test_roles.py
This commit in plone.app.locales changed several German strings:
https://github.com/collective/plone.app.locales/commit/426adfc06bbc94eeddf350ba6d7c93059372c6fd
Reviewer was mostly called 'Redacteur', and is called simply 'Reviewer' now.
And in one case it had been translated as 'Veröffentlichen', which is what plone.restapi was testing,
but that one means 'make public', so it wasn't a good translation.
So Jenkins was broken in [5.2](https://jenkins.plone.org/job/plone-5.2-python-2.7/2103/testReport/plone.restapi.tests.test_roles/TestRolesGet/test_roles_endpoint_translates_role_titles/).
Updated the test to check for Reviewer instead.
cc @jzellinter who updated the German text. No one is to blame for the test failure, as you can't know that it breaks. Just checking in to see if I am …
> Fixed tests after German translation update.

- docs/source/readthedocs-requirements.txt
- requirements.txt
This is to avoid an [issue in version `0.10.0`](https://github.com/collective/sphinxcontrib-httpexample/issues/41) that prevents requests/responses being included from the filesystem, e.g. using the `:request:` option.
In the medium / long term, we should
- clean up the requirements in `plone.restapi` (duplication between `requirements.txt` and ? `docs/source/readthedocs-requirements.txt`)
- switch the ReadTheJobs build to use the same requirements that are used for local development / docs builds.
For now, this should fix the issue at hand - the HTTP examples not being rendered in our docs. Even though we pinned `0.7.0` in the package root `requirements.txt`, what was previously being used by RTD would have been `0.9.1` - that's why I'm pinning it to that version, and also bumping the …
> Pin sphinxcontrib-httpexample==0.9.1 in readthedocs-requirements.txt:

- .travis.yml
- src/plone/restapi/services/__init__.py
- src/plone/restapi/tests/test_documentation.py
* Keep space after JSON items
* Use port 55001 on travis
* Be sure to flush file before writing request body
There are still some differences in the output in Python 3 but now it's much easier to see the real differences.
> Fix some differences with http test output in Python 3

- src/plone/restapi/tests/test_documentation.py
`transaction` is already imported globally at the top.
[ci-skip]
> Remove duplicated import

- CHANGES.rst
- src/plone/restapi/tests/test_documentation.py
This prevents lots of ResourceWarnings about unclosed sockets.
Fixes https://github.com/plone/plone.restapi/issues/636 and https://github.com/plone/plone.restapi/issues/648.
> Close the api_session in tests.

- CHANGES.rst
- src/plone/restapi/testing.py
On Jenkins we often get one ConnectionError in a seemingly random test.
Happens on both Python 2 and 3.
Retrying after a short pause helps.
Fixes https://github.com/plone/plone.restapi/issues/648
Note: I added a print statement so we know if it happens, and maybe detect a pattern in the urls where this goes wrong. I tried `logger.warning` and `logger.error`, but this never showed up in the test output.
In a few local parallel runs, I have seen errors on these urls:
```
http://localhost:64140/plone/@users
http://localhost:64117/plone/@types/Document
http://localhost:49516/plone/@users/noam
```
> Tests: retry request on ConnectionError.

- CHANGES.rst
- plone-4.3.x.cfg
How come we need to pin six up for 4.3? Or is 4.3 not a compatibility target for master anymore?
Never the less, the tests do pass when one pins six to `1.11.0`.
Green on Travis again.
> Pin six to 1.11.0 for plone-4.3.x.cfg to be buildoutable again

- README.rst
The example API URLs in the docs are `http` whereas the actual route is `https`. On making a request to the endpoint mentioned in the docs using `curl` responds with HTTP 301 error code :arrow_down: 
```
HTTP/1.1 301 Moved Permanently
Server: nginx/1.14.2
Date: Sun, 24 Feb 2019 08:41:36 GMT
Content-Type: text/html
Content-Length: 185
Connection: keep-alive
Location: https://plonedemo.kitconcept.com/
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.14.2</center>
</body>
</html>
```
> docs : HTTP 301 err on EXAMPLE APIs in docs

- news/682.feature
- news/684.bugfix
- setup.cfg
- setup.py
- the release version must use periods between micro and suffix (if any), otherwise setuptools keeps complaining about it
- universal wheels can not be built due to a check on setup.py regarding which python version is being used to install the package
> Fix release

- news/689.bugfix
- src/plone/restapi/services/content/tus.py
- src/plone/restapi/tests/test_tus.py
- When a file is created with TUS upload, fire created et al. events.
- When a file is replaced with TUS upload, fire modified event.
- Acquisition wrap newly created objects during deserialization.
> Fix TUS upload events

- docs/source/upgrade-guide.rst
- news/691.breaking
- src/plone/restapi/deserializer/configure.zcml
- src/plone/restapi/deserializer/dxfields.py
- src/plone/restapi/serializer/configure.zcml
- src/plone/restapi/serializer/controlpanels.py
- src/plone/restapi/serializer/dxfields.py
- src/plone/restapi/serializer/relationfield.py
- src/plone/restapi/tests/dxtypes.py
- src/plone/restapi/tests/test_dxfield_deserializer.py
- src/plone/restapi/tests/test_dxfield_serializer.py
Fixes #691 
Deserialization from term values still works, however serialization always returns the token.
This may break compatibility with API clients if the term's value is not equal to it's token.
> Use tokens for serialization and deserialization of vocabulary terms

- news/721.bugfix
- src/plone/restapi/services/auth/renew.py
- src/plone/restapi/tests/test_auth.py
When renewing an expired or invalid authentication token with ``@login-renew`` fail with a ``401`` error instead of returning a new authentication token.
Fixes #721
> Fail when renewing invalid authentication tokens.

- news/745.bugfix
- src/plone/restapi/testing.py
- src/plone/restapi/tests/test_time_freezing.py
Our patch for `ZODB.utils.newTid` got made ineffective by internal API changes in `freezegun`:
The patch, which was supposed to ensure that `ZODB.utils.newTid` always uses the real time functions (never the patched ones) relied on an attribute `previous_time_function` being present on the patched `time.time()`, in order to recognize time being patched and access the original, real time function.
That was true for an older version of `freezegun`, but since `0.3.12` it stows aways references to the original time functions in [module globals in `freezegun.api` (`real_time`, `real_gmtime`, etc)](https://github.com/spulec/freezegun/blob/64a0541cec8e9e3d7b63fdccb80db19cd7a613fe/freezegun/api.py#L24-L30). The `previous_time_function` reference to the original time function got removed during a …
> Fix time freezing in Plone 5.1 tests

- news/742.bugfix.1
- news/742.bugfix.2
- news/743.bugfix
- src/plone/restapi/serializer/vocabularies.py
- src/plone/restapi/tests/test_services_vocabularies.py
I'm addressing three categories of vocabulary term serialisation failures we've encountered when trying to bump `plone.restapi`.
I'm not super confident about having done either fix well, so please review with a critical eye.
Closes https://github.com/plone/plone.restapi/issues/742
Closes https://github.com/plone/plone.restapi/issues/743
> Robustify the vocabularies serializer

- news/748.bugfix
- src/plone/restapi/tests/test_types.py
- src/plone/restapi/types/adapters.py
A `defaultFactory` might be context aware (if it implements `IContextAwareDefaultFactory`).
However, in order for these context aware default factories to be invoked with the correct context, the field needs to be bound first before attempting to access `field.default`. The `DefaultJsonSchemaProvider` used in the `@types` endpoint currently doesn't do this, and therefore always invokes `field.default` on unbound fields.
This change makes sure the `DefaultJsonSchemaProvider` (and providers inheriting from it) always operates on bound fields.
Fixes #748
> types endpoint: Fix support for context aware default factories

- news/760.bugfix
- src/plone/restapi/services/workflow/transition.py
- src/plone/restapi/tests/test_workflow.py
https://github.com/plone/volto/issues/761
#760
> Effective date not set

- docs/source/conf.py
- news/764.bugfix
This adds `application/json+schema` to the list of MIME types that the Pygments JSON lexer is registered to handle. This will fix **syntax highlighting** for our large **JSON schema dumps** in the documentation of the `@types` endpoint.
See [before](https://plonerestapi.readthedocs.io/en/latest/types.html) and [after](https://plonerestapi.readthedocs.io/en/syntax-highlight-jsonschema/types.html) _(example response at the bottom of those pages)_.
Fixes #764
> Docs: Make sure application/json+schema examples also get syntax highlighted.

- news/771.feature
- src/plone/restapi/services/users/get.py
The permission checks in the `@users` endpoint were [hardcoded in the `reply()` method](https://github.com/plone/plone.restapi/blob/master/src/plone/restapi/services/users/get.py#L51-L105). This makes it quite cumbersome to override this endpoint to just do different permission checks for who should be allowed to enumerate, query and access user information.
This PR simply factors them out into individual methods, so that the endpoint can more easily be customized.
Fixes #771
> Factor out permission checks in @users endpoint.

- news/729.bugfix
- src/plone/restapi/imaging.py
- src/plone/restapi/tests/test_dxfield_serializer.py
Because on `POST` we also return the serialized, created object in the response, the serialization of image scales produced a confusing error when uploading a corrupt or possibly misnamed image.
Since it is, at least in some cases, also possible to get corrupted images into Plone using the classic user interface, I opted for not guarding against that in `plone.restapi`.
Instead, I modified the code for serializing image scales in a way that it fails gracefully. For corrupt images, it will now
- return `None` as the download URL
- return an empty scales dict
- return a width and height of `-1`
Fixes #729
> Gracefully handle corrupt images when serializing scales.

- news/777.bugfix
- src/plone/restapi/deserializer/relationfield.py
- src/plone/restapi/tests/test_dxfield_deserializer.py
Return status `400` (instead of `500`)  if a referenced object can not be resolved during deserialization since it's a client error.
Fixes #777.
> Return status 400 if a referenced object can not be resolved during deserialization

- news/802.bugfix
- src/plone/restapi/deserializer/dxcontent.py
- src/plone/restapi/tests/test_dxcontent_deserializer.py
Setting a field to null in a PATCH request, was not tracked as field change in the DX Content deserializer and therefore no ModifiedEvent was fired. Closes #802 
Besides that, I split up the call method to make code analysis checks happy.
> Fire ModifiedEvent when field is set to null in a PATCH request.

- news/2952.bugfix
- src/plone/restapi/configure.zcml
This is instead of using `includeDependencies`.
See https://github.com/plone/Products.CMFPlone/issues/2952
> Explicitly load zcml of dependencies

- news/788.bugfix
- src/plone/restapi/serializer/dxfields.py
- src/plone/restapi/tests/dxtypes.py
- src/plone/restapi/tests/test_dxfield_serializer.py
Vocabulary items are not hashable and thus we can't cast them to the
fields type. We always return lists as JSON doesn't support other
container types anyway.
Closes #788
> Fix issue with serialization of vocabulary items

- news/825.bugfix
- src/plone/restapi/profiles/testing/types/DXTestDocument.xml
- src/plone/restapi/serializer/vocabularies.py
- src/plone/restapi/tests/dxtypes.py
- src/plone/restapi/tests/helpers.py
- src/plone/restapi/tests/test_services_sources.py
- src/plone/restapi/tests/test_services_vocabularies.py
This fixes an issue where on Python 2 filtering `@vocabularies` or `@sources` by a `title` that contains non-ASCII characters.
Because request parameters are parsed into UTF-8 encoded bytestrings on Python 2, this leads to a bytestring search query getting compared with unicode term titles. If the search query contains non ASCII characters, the implicit decoding using the default encoding will fail. Making sure we always compare `unicode` (or `str` on Python 3) fixes this.
*(Filtering by `token` doesn't need the same treatment because tokens can [only be 7-bit ASCII](https://github.com/zopefoundation/zope.schema/blob/master/src/zope/schema/interfaces.py#L884-L891))*
Fixes #825
> Fix filtering vocabs and sources by non-ASCII title

- docs/source/upgrade-guide.rst
- news/827.bugfix
- src/plone/restapi/deserializer/mixins.py
- src/plone/restapi/tests/mixin_ordering.py
- src/plone/restapi/tests/test_upgrade_ordering.py
- src/plone/restapi/upgrades/configure.zcml
- src/plone/restapi/upgrades/ordering.py
This PR fixes an issue where ids of reordered content are converted to unicode on python 2. We now convert input ids when necessary and make sure the ordering stored on a container contains only bytestring object ids.
When changing object ordering via PATCH request we used to incorrectly store ids of reordered resources as unicode instead of a bytestring (on python2). This lead to mixed types being stored in the ordering annotations and subsequently mixed types being returned when calling `objectIds` of a container.
The problem only exists with python2 as python3 uses unicode internally.
Things we should probably discuss in this PR:
- Is the suggested upgrade-path feasible?
- The current suggestion pushes responsibility to upgrade ordering to the client, see suggestion in upgrade-guide. …
> Prevent converting bytestring ids to unicode ids when reordering on python2.

- news/819.bugfix
- src/plone/restapi/interfaces.py
It's not used in plone.restapi and should be imported from plone.rest.interfaces instead. If anybody was using this marker, it didn't do anything.
We coul alias/import it from plone.rest to here, but then it suddenly would start to work..... I don't know if that's better than removing it.
> Remove IAPIRequest marker interface

- news/844.feature
- src/plone/restapi/configure.zcml
- src/plone/restapi/indexers.py
- src/plone/restapi/indexers.zcml
- src/plone/restapi/tests/test_blocks_searchable_text.py
- versions.cfg
Used in volto for documents and objects implementing IBlock interface and using blocks
> Add SearchableText indexing for text in blocks

- CONTRIBUTORS.rst
- news/376.bugfix
- src/plone/restapi/serializer/summary.py
- src/plone/restapi/testing.py
- src/plone/restapi/tests/test_content_get.py
Fix the WorkflowException when requesting a fullobject with a related item that doesn't have a workflow (see issue #376).
I added one test about this topic. When tryint to run all `TestContentGet` I saw that all of them were skipped. I had to remove the check at the top of the test class:
```
if not HAS_AT:
raise unittest.SkipTest("Skip tests if Archetypes is not present")
```
because this is a DX test.
For compatibilty reasons, do we need to add a HAS_DX check here?
> Fix related item review state 376

- plone-4.3.x.cfg
This adds version constraints to `plone-4.3.x.cfg` needed for Python 2.7 compatibility.
Fixes build failures like these:
https://travis-ci.org/plone/plone.restapi/jobs/640324488
> Fix Plone 4.3.x build

- news/857.bugfix
- src/plone/restapi/deserializer/local_roles.py
- src/plone/restapi/tests/test_content_local_roles.py
This fixes the privilege escalation issue in the `@sharing` endpoint described in #857 (patched in `PloneHotfix20200121`).
I verified once more that the
- test fails if the vulnerability in the code isn't fixed yet
- passes once its fixed
for both Plone 5.2 and Plone 4.3.
Closes #857
> Sharing POST: Limit roles to ones the user is allowed to delegate.

- src/plone/restapi/tests/test_services_types.py
This is a followup for the merged #873. I overlooked this failure at first.
See [Jenkins job](https://jenkins.plone.org/job/pull-request-5.2-3.7/946/testReport/junit/plone.restapi.tests.test_services_types/TestServicesTypes/test_addable_types_for_non_manager_user/).
> Use longer password in another test.

- news/642.bugfix
- setup.py
See https://github.com/plone/buildout.coredev/issues/642#issuecomment-597008272
I have been fixing this in several packages.
> Fixed package install error with Python 3.6 without locale.

- news/842.bugfix
- src/plone/restapi/tests/test_services_querystring.py
plone.app.discussion introduces an additional workflow. This change takes the additional workflow states into account.
> Update test: plone.app.discussion

- news/905.bugfix
- plone-5.2.x.cfg
>  Refs #905 - Fix sphinxbuilder with Python 3.8

- docs/source/controlpanels.rst
- src/plone/restapi/controlpanels/interfaces.py
- src/plone/restapi/controlpanels/types.py
> Refs #534 - Control Panels: dexterity-types

- news/914.bugfix
- src/plone/restapi/tests/test_behaviors.py
Small fix in IBlocks test, added an assert call that was missing.
> Fix test for IBlocks behavior

- news/913.bugfix
- src/plone/restapi/deserializer/dxfields.py
- src/plone/restapi/tests/test_content_patch.py
- src/plone/restapi/tests/test_content_post.py
- src/plone/restapi/tests/test_dxfield_deserializer.py
This will fix [#1250](https://github.com/plone/volto/issues/1250) for Volto.
We could receive html with some html entities that potentially broke some Plone parts (portal_transform in this case).
With this fix, we perform a cleanup before store data to Plone
> Fix richtext encoding in deserializer

- Makefile
- news/911.feature
- plone-5.2.x.cfg
- src/plone/restapi/services/querystringsearch/configure.zcml
- src/plone/restapi/services/querystringsearch/get.py
- src/plone/restapi/tests/test_services_querystringsearch.py
The tests will fail until https://github.com/zopefoundation/Products.ZCatalog/pull/99 is merged and released.
> Make the querystring-search endpoint context aware

- docs/source/searching.rst
- Remove duplicate word
- Minor wording
- Match the query to the examples below
- Small grammar fixes
- Small punctuation and word order issues.
> Minor @search documentation fixes

- news/932.bugfix
- src/plone/restapi/tests/test_dxfield_serializer.py
This fixes are needed to fix the tests with the original image scale handling fixes in plone.namedfile
Those changes are in this PR and both branches should be tested together:
https://github.com/plone/plone.namedfile/pull/92
> Adapt imagefield serializer tests 

- news/956.bugfix
- src/plone/restapi/services/database/configure.zcml
to avoid ConfigurationExecutionError regarding 'plone.app.controlpanel.Overview' permission while starting Plone 4.3.x, see #956
I added the same fix explained in #526 in configure.zcml of services/database
I think yhis could be done in the services/configure.zcml where we already include CMFCore permissions because service "system" that also use the permission would have the same problem if permission was not loaded in database configure.zcml
So if you think it is better to move it to the parent's configure.zcml, I may change it.
Thank you for review and merge!
Gauthier
> Include plone.app.controlpanel permissions.zcml in database service

- news/957.bugfix
- src/plone/restapi/serializer/collection.py
- src/plone/restapi/tests/test_serializer.py
Hi,
this is a fix for #957, it takes include_items parameter into account in SerializeCollectionToJson.
Please review and merge if ok!
Thank you,
Gauthier
> - Take the `include_items` parameter into account in `SerializeCollectionToJson`, see #957

- news/970.bugfix
- setup.py
- src/plone/restapi/search/handler.py
- src/plone/restapi/serializer/catalog.py
... since it is handled in DefaultJSONSummarySerializer, see #970
Removing it from search still let tests pass as it was not used, computed in search then computed again in DefaultJSONSummarySerializer...
This cleaning is necessary to avoid using it in search using the parameter as it is not taken into account and done after from request.form
Please review, comment, merge, ... ;-)
Thank you!
Gauthier
> Removed useless management of metadata_fields in SearchHandler/LazyCatalogResultSerializer

- news/975.bugfix
- src/plone/restapi/testing.py
- src/plone/restapi/tests/test_documentation.py
- src/plone/restapi/tests/test_serializer_summary.py
- src/plone/restapi/types/utils.py
Note: zope.component.hooks already works in Plone 4.3.
Part of https://github.com/plone/plone.restapi/issues/975
> Fixed deprecation warnings for zope.site.hooks and ILanguageSchema.

- plone-4.3.x.cfg
- plone-5.0.x.cfg
- plone-5.1.x.cfg
This is the last pyrsistent version that is python 2 compatible.
On 5.2 it is pinned in the core versions.
It is a dependency of jsonschema.
Just a Travis test fix, so no changelog entry, and no Jenkins jobs needed.
> Pin pyrsistent to 0.15.7 in buildout configs.

- news/3178.bugfix
- src/plone/restapi/tests/test_services_email_notification.py
- src/plone/restapi/tests/test_services_email_send.py
- src/plone/restapi/tests/test_services_users.py
Part of https://github.com/plone/Products.CMFPlone/issues/3178
Should be tested together with other PRs from that issue.
But the tests here in `plone.restapi` should still pass with older Products.MailHost and older Plone. So if tests are green, it could be merged.
> Fix tests with Products.MailHost 4.10.

- news/1001.bugfix
- src/plone/restapi/tests/test_services_types.py
See https://github.com/plone/plone.dexterity/pull/137
> Refs #1001 - Make tests more generic

- news/1019.bugfix
- src/plone/restapi/services/groups/add.py
- src/plone/restapi/services/users/add.py
On Python 2 it could be unicode for the users and groups end points.
Fixes https://github.com/plone/plone.restapi/issues/1019
> Fix Zope 4.5.2 compatibility: make sure Location header is string [master]

- news/1009.feature
- src/plone/restapi/deserializer/dxcontent.py
I got an difficult to interpret traceback on content POST like:
```
2020-10-30 15:50:32,222 ERROR   [Zope.SiteErrorLog:252][waitress-3] 1604069432.22186450.03333581790354878 http://localhost:8080/Plone/reviere/POST_application_json_
Traceback (innermost last):
Module ZPublisher.WSGIPublisher, line 167, in transaction_pubevents
Module ZPublisher.WSGIPublisher, line 364, in publish_module
Module ZPublisher.WSGIPublisher, line 259, in publish
Module ZPublisher.mapply, line 85, in mapply
Module ZPublisher.WSGIPublisher, line 68, in call_object
Module plone.rest.service, line 22, in __call__
Module plone.restapi.services, line 20, in render
Module plone.restapi.services.content.add, line 77, in reply
Module plone.restapi.deserializer.dxcontent, line 45, in __call__
Module …
```
> Improve import traceback

- .gitignore
- .travis.yml
- plone-5.2.x.cfg
This is a backport of https://github.com/plone/plone.restapi/pull/1013 because Travis fails on the 6.x.x branch as well.  See for example:
https://travis-ci.org/github/plone/plone.restapi/jobs/743167173
> Fix Travis on 6.x.x.

- versions.cfg
PyJWT >= 2.0.0 drop support for Python 2. See:
https://github.com/jpadilla/pyjwt/blob/2.0.0/setup.cfg#L25
This fix: https://github.com/plone/plone.restapi/runs/1624633682
> Pin PyJWT = 1.7.1 for Plone 5.1 and Plone 4.3

- news/1066.bugfix
- src/plone/restapi/search/handler.py
- src/plone/restapi/tests/test_search.py
In [Products.CMFPlone](https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/CatalogTool.py#L423) there is a method that checks if the current user has that permission in the list of paths in kw.
In @search handler we call _searchResults_ method passing a query and not kw.
This leads to a problem because if you give that permission to some roles (Editor for example) and you give Editor role to an user in a subfolder, the @search endpoint will not show expired contents in that folder even if the user has the right permission.
You can test it easily with Volto because the "/contents" view does exactly the problematic @search call:
- add Editor to "Access inactive portal content" permission
- assign Editor role to an user inside a subfolder
- create an expired content …
> Respect access inactive content permission in @search

- docs/source/searching.rst
- news/1081.feature
- src/plone/restapi/search/handler.py
- src/plone/restapi/services/search/get.py
- src/plone/restapi/tests/test_search.py
The `@search` endpoint can now follow Plone's settings if a `use_site_search_settings` parameter is passed in the request.
This means that the types will be filtered, the navigation root will be respected and the default sort order will be used.
> Optional search endpoint follows site settings

- news/1113.bugfix
- src/plone/restapi/services/history/get.py
- src/plone/restapi/tests/test_services_history.py
The re-used viewlet returns `None` in its `fullHistory` when there is no (visible) workflow history and when there is no (visible) revision history.
We did not take this into account and always attempt to iterate the returned value, which will fail for `None` for obvious reasons.
I'm adding a simple fix for the issue by initializing the value to an empty list in such cases.
Fixes #1113
> Fix `@history` when full history is empty.

- .github/workflows/ci.yml
- news/1121.breaking
- setup.cfg
- setup.py
https://packaging.python.org/guides/dropping-older-python-versions/
> Drop support for Python 2 and Plone 5.1 and 4.3.

- src/plone/restapi/tests/test_batching.py
The default ordering of Plone is by `relevance`. Therefore, it is not guaranteed that all searches without `sort_on`, have the same order.
Listings of contents of folders and collections with batch don't accept `sort_on`. In such cases, without `sort_on` it is not possible to force a different order of `relevance`.
Because of this, this test had intermittent failures.
Error:
```bash
Failure in test test_contains_correct_batch_of_items (plone.restapi.tests.test_batching.TestBatchingSearch)
Traceback (most recent call last):
File "/opt/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/unittest/case.py", line 329, in run
testMethod()
File "/home/runner/work/plone.restapi/plone.restapi/src/plone/restapi/tests/test_batching.py", line 110, in test_contains_correct_batch_of_items …
```
> Fix intermittent failures in test_batching

- versions.cfg
This is the latest version compatible with Python 2. See:
https://github.com/mgedmin/check-manifest/blob/920816f6fd9c1c4d21f8322398f493d544ae6f76/setup.py#L47
This also fix the error:
```bash
Version and requirements information containing toml:
[versions] constraint on toml: 0.9.6
While:
Requirement of check-manifest: toml
Installing.
Requirement of build>=0.1: toml>=0.10.0
Getting section code-analysis.
Initializing section code-analysis.
Installing recipe plone.recipe.codeanalysis.
Error: The requirement ('toml>=0.10.0') is not allowed by your [versions] constraint (0.9.6)
```
in Plone 5.1.
Fix: https://github.com/plone/plone.restapi/runs/2656778250?check_suite_focus=true
> Pinn check-manifest = 0.4.1 in Python 2

- news/895.bugfix
- setup.py
- src/plone/restapi/__init__.py
- src/plone/restapi/patch.py
- src/plone/restapi/tests/test_setup.py
Plone 4.3 considers that the first profile, after ordering all profiles in alphabetical order, is the profile to be installed when installing
the product. Since plone.restapi has the profile `blocks`, it is installed, instead of the default profile. This patch puts the `default` profile in the first position, so that it is the installed profile.
Fix #895
> Patch Plone 4.3's _install_profile_info method to list the default profile of plone.restapi in the first position.

- .gitignore
- news/1141.bugfix
- src/plone/restapi/pas/plugin.py
- src/plone/restapi/services/auth/login.py
- src/plone/restapi/tests/test_functional_auth.py
Fix some behavior in the PAS plugin that treated API login requests differently than
classic HTML form login requests, namely that the POST'ed login credentials weren't
extracted and authenticated like they are when the classic HTML login form is POST'ed.
IMO, the root cause here was a minor case of not actually fulfilling the PAS plugin
interface.  In the case of the classic HTML login form, it's another PAS plugin that
extracts the POST'ed credentials, but since the API login POST submits JSON, it has to
be the JWT plugin that extracts them.
Also reproduce the same handling that the classic Plone HTML login form does after login
has succeeded.  This includes setting the classic HTML login form cookie so that
authenticating to the API also authenticates the user to the classic HTML UI …
> fix(auth): Unify ZMI, HTML form, and API login

- news/1158.bugfix
- src/plone/restapi/batching.py
- src/plone/restapi/deserializer/mixins.py
- src/plone/restapi/imaging.py
- src/plone/restapi/indexers.py
- src/plone/restapi/pas/plugin.py
- src/plone/restapi/serializer/converters.py
- src/plone/restapi/serializer/discussion.py
- src/plone/restapi/serializer/dxfields.py
- src/plone/restapi/services/addons/post.py
- src/plone/restapi/services/auth/login.py
- src/plone/restapi/services/content/tus.py
- src/plone/restapi/services/contextnavigation/get.py
- src/plone/restapi/types/adapters.py
Sorry, it hurts my eyes. So, be more pythonic and just return, pass or drop it and end of method/function.
> Eliminate non-pythonic 'return None' usage

- news/1166.bugfix
- src/plone/restapi/deserializer/configure.zcml
- src/plone/restapi/deserializer/dxfields.py
- src/plone/restapi/serializer/configure.zcml
- src/plone/restapi/serializer/dxfields.py
plone.restapi 7.0.0b2 introduced a serializer/deserializer for remoteUrl Link's field, in PR #1005.
This introduced an undeclared dependency on plone.app.contenttypes.
Solution: use conditional imports and use zcml:condition to register the serializer and deserializer.
Use case: collective.exportimport on Plone 4 loads `serializers/dxfields.py` and this fails without plone.app.contenttypes.
> Fix startup on Plone 4 without plone.app.contenttypes.

- docs/source/content.rst
- news/497.feature
- src/plone/restapi/services/content/add.py
- src/plone/restapi/tests/test_content_post.py
Allow setting UID of a content during creation if the user has Manage Portal permission.
If the user has no permission, the content is created but UID is not set.
> Set UID of a content during creation

- news/1184.bugfix
- src/plone/restapi/services/workflow/info.py
- src/plone/restapi/tests/test_workflow.py
There was only half checks for no workflow contents (on history)
> Do not break @workflow endpoint for contents without workflow

- news/1190.bugfix
- src/plone/restapi/services/workflow/transition.py
- src/plone/restapi/tests/test_workflow.py
Do not break with a 400 if we are trying to change wf for a content without workflow.
I wanted to fix that on children contents but right now it does not return a 400 also if we try to call this action directly on a content without a workflow. Should we keep the 400 error in this case?
> Skip doActionFor for items without workflow

- news/2454.bugfix
- src/plone/restapi/tests/test_services_controlpanel_dexterity_types.py
This is what is left over from https://github.com/plone/plone.restapi/pull/1200
> Updated tests to not fail when the Plone Site root is dexterity.

- base.cfg
In Python 3.8, for the TZ environment variable to be recognized, you
need to call time.tzset()
Ref: https://github.com/plone/buildout.coredev/pull/701
This is a backport of #1195 to branch 7.x.x
> Fix tests that involving dates in Python 3.8 on machines that don't use TZ=UTC

- news/1222.bugfix
- src/plone/restapi/services/users/get.py
> Order users by fullname.

- src/plone/restapi/tests/test_services_types.py
Fix #1018 
The problem is that `plone.dexterity 2.10+` now uses the `_p_mtime` variable in the schema names. See:
https://github.com/plone/plone.dexterity/pull/137
As this variable is related to date/time and the tests are executed very fast, some schema had the same name, when they shouldn't
be. This was causing problems in the tests. So i introduce sleeps in Plone 5.2 with Python 2, so that the schemas don't have the same names.
In Python 3 we don't have this problem because the precision of `_p_mtime` is higher in Python 3.
> Fix random failures on test_services_types

- base.cfg
- news/1226.bugfix
- src/plone/restapi/tests/http-examples/types_document.resp
- src/plone/restapi/tests/http-examples/types_document_get_field.resp
- src/plone/restapi/tests/http-examples/types_document_post_field.resp
- src/plone/restapi/tests/http-examples/types_document_put.req
- src/plone/restapi/tests/test_documentation.py
This is for master what I already [did on 7.x.x](https://github.com/plone/plone.restapi/pull/1218#pullrequestreview-754383233).
> Further normalise http-examples, and no port hardcoding

- news/1231.bugfix
- src/plone/restapi/serializer/catalog.py
- src/plone/restapi/tests/test_search.py
when using `@search` endpoint and a brain is orphan or a `KeyError` occurs during result serialization
See issue #1231
PS: if this is backported to version working with Zope2, there will need to change as getObject an orphan brain raises KeyError in Zope4 but an AttributeError in Zope2...
> Avoid `UnboundLocalError` or duplicates in results

- docs/source/searching.rst
The documentation says to use `depth` but this does not work, the correct parameter is `path.depth`
> fix the parameter name to get the current context item when using the @search endpoint

- news/1251.bugfix
- src/plone/restapi/tests/test_blocks_searchable_text.py
- src/plone/restapi/tests/test_search.py
- src/plone/restapi/tests/test_serializer_catalog.py
The following PR should be merged together:
https://github.com/plone/plone.app.content/pull/236
https://github.com/plone/plone.app.contentlisting/pull/39
https://github.com/plone/plone.app.contenttypes/pull/616
https://github.com/plone/plone.app.upgrade/pull/264
https://github.com/plone/plone.restapi/pull/1251
https://github.com/plone/Products.CMFPlone/pull/3343
> Adapt the tests for Plone 6

- plone-6.0.x.cfg
This fixes the build like it is defined now, but I think that the GHA workflows should be revisited.
Fixes #1254
> Checkout Products.CMFPlone to have a green GHA build again

- news/1250.feature
- src/plone/restapi/interfaces.py
- src/plone/restapi/serializer/configure.zcml
- src/plone/restapi/serializer/summary.py
This allows addons to extend the metadata returned by the Summary serializer
To always return **image_field** metadata on summaries, in an addon you will implement a new file called `summary,py` with content
```
from plone.restapi.interfaces import IJSONSummarySerializerMetadata
from zope.interface import implementer
@implementer(IJSONSummarySerializerMetadata)
class JSONSummarySerializerMetadata:
def default_metadata_fields(self):
return {
"image_field",
}
```
and register it with:
```
<utility factory=".summary.JSONSummarySerializerMetadata" name="plone.volto.summary_serializer_metadata" />
```
> Implement IJSONSummarySerializerMetadata

- news/1267.bugfix
- src/plone/restapi/services/addons/addons.py
For some reason I got an `Products.CMFQuickInstaller` import error in Plone 6. Maybe because its gone? Question is why it worked in past? Did it?
Anyway, this fixes the problem.
> Remove all traces of Products.CMFQuickInstaller

- src/plone/restapi/tests/test_serializer.py
- src/plone/restapi/tests/test_services_querystringsearch.py
**test_serialize_to_json_collection_include_items:**
When we don't have the `sort_on` parameter, it's not guaranteed that the search result will always come in the same order. This was causing the test to fail randomly. So we sort the titles before comparing the result.
This fixes the error:
```
AssertionError: 'Document 2' != 'Document 1'
```
See: https://jenkins.plone.org/job/pull-request-6.0-3.9/561
**test_querystringsearch_complex:**
We add the `sort_on` parameter to ensure that the result always comes in the same order.
This fixes the error:
AssertionError: 'Test Document 8' != 'Test Document 4'
See: https://github.com/plone/plone.restapi/runs/4288557515?check_suite_focus=true
> Fix random failures in tests

- docs/source/vocabularies.rst
- news/1264.feature
- src/plone/restapi/serializer/vocabularies.py
- src/plone/restapi/tests/test_services_vocabularies.py
To provide a better support to the new select widget capabilities, we need to get the full thing, no batches.
> Return non-batched vocabularies given a query param b_size=-1

- news/1258.bugfix
- src/plone/restapi/services/vocabularies/configure.zcml
- src/plone/restapi/services/vocabularies/get.py
- src/plone/restapi/tests/test_services_vocabularies.py
- No check of field permissions: that's not the responsibility of the vocabulary, but of the schema.
> Lower restriction of vocabularies endpoint

- src/plone/restapi/tests/test_services_types.py
`plone.dexterity` 2.10+ uses the `_p_mtime` variable in the schema name. These sleeps were added because I thought `_p_mtime` was more precise in Python 3, but it was actually the `str` function, used to convert `_p_mtime`
from float to string, that was rounding off `_p_mtime`. Now `plone.dexterity` uses the `repr` function, which doesn't round float,
instead of `str`.
See: https://github.com/plone/plone.dexterity/pull/159
This revert: https://github.com/plone/plone.restapi/commit/39e4f20e41acad9fcd25cf850a42bbcdd47b7cd2
> Remove sleeps in test_services_types in Python 2

- news/1284.bugfix
- src/plone/restapi/services/vocabularies/get.py
- src/plone/restapi/tests/test_services_vocabularies.py
Small thing, return 401 also whenever it is sensible.
> Improve error status code in new vocabularies endpoint refactor

- news/1282.bugfix
- src/plone/restapi/deserializer/dxcontent.py
- src/plone/restapi/tests/dxtypes.py
- src/plone/restapi/tests/test_dxcontent_deserializer.py
- src/plone/restapi/tests/test_dxcontent_serializer.py
See #1282 .
Could be a conflictive piece of code, so please triple check this. Tricky thing here is that I guess that `missing_value` is a `zc3.form`/Classic UI thing, and we are transferring those responsibilities to the RESTAPI code here. One could argue that the frontend should take care of that instead than the API.
> Improve support for `missing_value` and `default` story

- docs/source/vocabularies.rst
- news/1294.feature
- src/plone/restapi/serializer/vocabularies.py
- src/plone/restapi/tests/http-examples/vocabularies_get_filtered_by_token_list.req
- src/plone/restapi/tests/http-examples/vocabularies_get_filtered_by_token_list.resp
- src/plone/restapi/tests/test_documentation.py
- src/plone/restapi/tests/test_services_vocabularies.py
> Enhance the vocabularies serializer to accept a list of tokens

- news/1291.bugfix
- src/plone/restapi/services/workflow/transition.py
- src/plone/restapi/tests/test_workflow.py
The problem is that if we have a private folder (A) with some children (AA AB AC) and one of these is already published (AB), the endpoint call returns a 400 because AB can't apply "publish" transition. The publication process will fail with some folders published (the ones before the published one) and other not (the ones after).
With this pr i will check if the current obj state is the same of the transition's destination and skip the exception. Otherwise, raise the error.
> Do not break if publish recursive folder children that are already published

- docs/source/vocabularies.rst
- news/1264.feature
- src/plone/restapi/serializer/vocabularies.py
- src/plone/restapi/tests/test_services_vocabularies.py
* Return non-batched vocabularies given a query param not_batched
* Change parameter name to b_size=-1
* Amend changelogg
> 7.x.x - Return non-batched vocabularies given a query param b_size=-1 (#1265)

- news/1307.feature
- src/plone/restapi/tests/test_services_querystring.py
Allow any additional property to be defined by plone.app.querystring,
otherwise no properties can ever be added. The change also makes sure
that all code depending on any existing attributes continues to work.
This is needed in favor of
https://github.com/plone/plone.app.querystring/pull/104 .
> Be permissive when testing the schema of the querystring endpoint

- news/1307.feature
- src/plone/restapi/tests/test_services_querystring.py
Allow any additional property to be defined by plone.app.querystring,
otherwise no properties can ever be added. The change also makes sure
that all code depending on any existing attributes continues to work.
This is needed in favor of
https://github.com/plone/plone.app.querystring/pull/104 .
> Be permissive when testing the schema of the querystring endpoint (#1306)

- .github/workflows/tests.yml
- news/1356.bugfix
- plone-6.0.x.cfg
This includes the fixes from my PR #1354.
The previous settings were fine for Plone 5.2, but not for 6.0. They tested unsupported Python 3.6, and were missing the supported Python 3.9.
We could have kept the two lists, but that would mean we need both an exclude (3.6) and an include (3.9). So instead I specify all valid combinations explicitly: for me this looks simpler.
> Fix testing matrix to use correct combos of Python and Plone.

- plone-6.0.x.cfg
Fixes buildout error for missing plone.base package, from the merged PLIP 3395.
See [failed run](https://github.com/plone/plone.restapi/runs/5856639094?check_suite_focus=true) on plone.restapi master.
> Checkout specific commit of CMFPlone.

- docs/source/conf.py
- news/1346.bugfix
Fix the link in the GitHub menu item "suggest edit" to point to master branch.
> Point to the correct repository branch for sphinx-book-theme

- docs/source/types-schema.md
- news/1379.bugfix
- Fixes #1370
- Remove u'' for Unicode Python 2 designator
- Convert from single to double quotes (blackify)
- Use correct lexers for both Zope and JSON code blocks
> Use JSON instead of JSON Schema for code samples

- news/1391.bugfix
- src/plone/restapi/services/history/get.py
Fixes https://github.com/plone/plone.restapi/issues/1391
> Fixed timestamp calculation in history service on Python 3.10.

- news/57.bugfix
- src/plone/restapi/tests/helpers.py
- src/plone/restapi/tests/test_documentation.py
- src/plone/restapi/tests/test_dxfield_serializer.py
- src/plone/restapi/tests/test_serializer.py
- src/plone/restapi/tests/test_services.py
This is only in serializer tests for images.
uuid4 is only used until plone.scale 6.0.0a4.
https://github.com/plone/plone.scale/pull/57 introduces a new way.
We also patch the _modified_since method to always return True.
Otherwise you may get info from a different scale back, precisely because we give all scales the same "unique" id,
which then is of course no longer unique, making the logic unstable.
This is needed for the newer plone.scale versions, but should be perfectly fine for the older ones.
The `plone.scale` PR allows us to get the urls without really generating the actual scales and store them in blobs. But this PR does **not** use it yet. Happy to do that, but that can be done slightly later, like after there is a new plone.scale release. With the current PR the tests are at …
> Tests: patch unique url for scale in old or new way.

- news/1428.bugfix
- src/plone/restapi/deserializer/utils.py
- src/plone/restapi/tests/test_blocks_deserializer.py
We had a some strange links in migrated data from a very old Plone. For example "../..".
With these changes, the method does not break and returns the given link.
> Do not break path2uid with strange links

- news/1327.feature
- news/1452.bugfix
- src/plone/restapi/serializer/user.py
- src/plone/restapi/tests/http-examples/users_filtered_by_groups.resp
- src/plone/restapi/tests/http-examples/users_filtered_by_username.resp
"test no uncommitted changes" fails, see for example [this run](https://github.com/plone/plone.restapi/runs/6806798950?check_suite_focus=true#step:12:67). No idea why the PR from earlier this week that added this was green.
(Plus tiny fix in an unrelated news snippet so another check is green.)
> Tests: fixed order of roles in http examples.

- news/49.bugfix
- src/plone/restapi/testing.py
- src/plone/restapi/tests/test_comments.py
- src/plone/restapi/tests/test_content_post.py
Needed to not fail with newer plone.outputfilters.
Similar to the fix in https://github.com/plone/plone.app.discussion/pull/202, see explanation there.
> Test-only fix: normalize white space in html in some tests.

- CHANGES.rst
- CONTRIBUTORS.rst
- news/1466.bugfix
- src/plone/restapi/serializer/user.py
This is a very minor PR.
Currently when checking for user portrait it checks to see if the user is in `memberdata.portraits` however it is not sanitising the user id, meaning some users don't get their portrait returned even if it exists. For example if there is a hyphen in the user id.
> Use _getsafeMemberId when checking for user portrait

- news/1461.bugfix
- src/plone/restapi/serializer/dxcontent.py
- src/plone/restapi/services/configure.zcml
Currently restapi depends on `plone.app.iterate`. 
The assumption, that it is always there, is wrong: it is an (internal) addon, only installed when dependening on 'Plone'.
> fix: plone.restapi must work with dependency on only Products.CMFPlone

- news/1448.bugfix
- src/plone/restapi/serializer/utils.py
Fixes: [#1448](https://github.com/plone/plone.restapi/issues/1448)
Changes:
- Pass unrestricted keyword argument to uuidToObject()
- The unrestricted argument value is set to True
Setting the unrestricted flag to True invokes the unrestrictedTraversal() method instead of the restrictedTraversal() method as shown [here](https://github.com/plone/plone.app.uuid/blob/65cdc16a81a9ed12453829fd3fd37d3aca5ac328/plone/app/uuid/utils.py#L94-L96). Earlier, invoking the latter threw the Unauthorized Exception. Now the access to the object can be controlled using the unrestricted flag. This will help in deprecating uuidToObject() from plone.outputfilters.browser.resolveuid.
> Add unrestricted keyword argument to uuidToObject()

- news/1448.bugfix
- src/plone/restapi/serializer/utils.py
PR #1471 depends on a version of `plone.app.uuid`, which has not been released yet. See:
https://github.com/plone/plone.restapi/pull/1471#issuecomment-1225594991
This fixes the broken tests.
Could not revert with git command.
> Revert PR #1471

- plone-5.2.x.cfg
- plone-6.0.x.cfg
- requirements-5.2.txt
- requirements-6.0.txt
- requirements.txt
- src/plone/restapi/tests/http-examples/querystring_get.resp
- src/plone/restapi/tests/http-examples/registry_get_list.resp
- src/plone/restapi/tests/http-examples/translated_messages_addons.resp
For a PR to be accepted, it needs to pass Jenkins tests. In Jenkins, the buildout pins the newest versions. So Plone latest is "closer" to Jenkins, than a pinned version of Plone, which ends up being outdated for a long time. Testing with the most similar versions decreases the chances of the test passing on github and failing on Jenkins, and vice versa.
> Use Plone latest in buildout

- news/1498.feature
- src/plone/restapi/imaging.py
- src/plone/restapi/serializer/dxfields.py
- src/plone/restapi/tests/test_dxfield_serializer.py
When available, use the new `pre` flag on the scale method of the imaging view so that we can serialize metadata about image scales without actually generating the scales. Improves performance and consequently should also reduce the chance of conflict errors.
> Don't generate image scales until they are needed

- .github/workflows/tests.yml
- .gitignore
- Makefile
- buildout.cfg
- news/1503.feature
- src/plone/restapi/tests/http-examples/controlpanels_get.resp
- src/plone/restapi/tests/http-examples/controlpanels_get_dexterity.resp
- src/plone/restapi/tests/http-examples/controlpanels_get_dexterity_item.resp
- src/plone/restapi/tests/http-examples/controlpanels_post_dexterity_item.resp
- src/plone/restapi/tests/http-examples/expansion_expanded_full.resp
- src/plone/restapi/tests/http-examples/image.resp
- src/plone/restapi/tests/http-examples/jwt_logged_in.resp
- src/plone/restapi/tests/http-examples/newsitem.resp
- src/plone/restapi/tests/http-examples/registry_get_list.resp
- src/plone/restapi/tests/http-examples/search.resp
- src/plone/restapi/tests/http-examples/siteroot.resp
- src/plone/restapi/tests/http-examples/translated_messages_addons.resp
- src/plone/restapi/tests/http-examples/translated_messages_types_folder.resp
- src/plone/restapi/tests/http-examples/vocabularies.resp
- src/plone/restapi/tests/http-examples/workingcopy_baseline_get.resp
- test-no-uncommitted-doc-changes
Update GHA to remove checks on Python 3.6 and added 3.10 for Plone 6. Removed 3.7 from Plone 6 as well.
The amendment in Makefile was needed because of 
https://community.plone.org/t/plone-6-0-0b2-released/15643
we were initially installing the 5.x buildout then on the top the Plone 6 one. This provoked the build to fail due that an initial outdated setuptools+zc.buildout was already in place. Now it only does it once, for each. Thus, the `Makefile` amendment.
> Plone 6 as first class citizen

- Makefile
- news/1517.internal
- plone-5.2.x.cfg
`plone.recipe.codeanalysis` was removed from buildout. The `importlib-metadata` pin was needed only because of code-analysis. So we're removing the pin.
Ref: #1507
> Remove code-analysis from Makefile

- news/1524.bugfix
- src/plone/restapi/serializer/discussion.py
- src/plone/restapi/serializer/user.py
- src/plone/restapi/services/users/get.py
- src/plone/restapi/tests/http-examples/translated_messages_addons.resp
- src/plone/restapi/tests/test_comments.py
- src/plone/restapi/tests/test_services_users.py
The previous pr #1466 resolved an issue where the endpoint was returning unsanitized user id's.
Following #1481 the new @portrait endpoint does not require sanitized user id's so when email login is enabled, portraits break.
The solution would either be to revert the change made in #1466 and return the raw user id, or to update the @portrait endpoint to handle sanitized id's.
This PR does the latter as well as:
- Updating the endpoint for discussion/comments to use the new url
- Updates the tests
- Uses a Plone user instead of the zmi admin user, as this causes issues rendering the portrait
- Adds a tests for users where login by email is enabled
- Updates comments tests
> Fix portrait endpoint for email address user id's

- news/1520.bugfix
- src/plone/restapi/tests/test_statictime.py
Needed for https://github.com/plone/plone.app.discussion/pull/204
Tests won't pass until https://github.com/plone/plone.app.discussion/pull/204 is merged as it is a co-dependent change.
Updating p.a.discussion to set timezone aware times.
The current test is checking for a timezone, but there isn't one so the following code wasn't getting executed:
```
if pydt.tzinfo is not None:
now = pydt.tzinfo.localize(now)
```
but `pydt.tzinfo.localize` is not a function so I have removed this check.
As the times coming from p.a.discussion will be tz aware, this update fixes the tests to compare using timezones.
> Fix test_statictime for p.a.discussion comments

- news/1530.bugfix
- src/plone/restapi/services/history/get.py
- src/plone/restapi/tests/http-examples/history_get.resp
- src/plone/restapi/tests/http-examples/translated_messages_addons.resp
- src/plone/restapi/tests/http-examples/translated_messages_object_history.resp
Fixes #1530
The api returns time information of the entries without a timezone specifier. See https://stackoverflow.com/questions/71024015/how-to-get-timezone-from-iso-time-string-in-python for a deeper explanation.
The lack of the timezone specifier causes Intl (and derivative libraries such as the FormattedDate component of react-intl) in the browser not to use local time, which is disturbing for the user who accepts local time. Thus this is considered a bug in applications.
To solve the problem we can add the timezone specifier to the end of the datetime string. Since the python timestamp does not contain the information about the originating timezone itself, this is always UTC and we can simply add Z to the end in all cases. This ensures that the date will be interpreted properly by …
> fix time to be returned with a timezone specifier

- news/1538.bugfix
- src/plone/restapi/tests/helpers.py
- src/plone/restapi/tests/http-examples/translated_messages_addons.resp
- src/plone/restapi/tests/test_documentation.py
This way we do not have to update plone.restapi's version in documentation tests each time a new release is created.
Fixes #1538
> Mock addon versions in documentation tests

- news/1553.bugfix
- src/plone/restapi/blocks_linkintegrity.py
- src/plone/restapi/tests/test_blocks_linkintegrity.py
> Make sure slate block linkintegrity retriever doesn't return None

- news/1548.feature
- src/plone/restapi/locales/de/LC_MESSAGES/plone.restapi.po
- src/plone/restapi/locales/plone.restapi.pot
- src/plone/restapi/services/users/add.py
- src/plone/restapi/services/users/update.py
- src/plone/restapi/tests/test_services_users.py
The `plone.restapi` domain was used.
Fixes https://github.com/plone/volto/issues/3958
> Internationalization of @users endpoint error messages

- news/1558.bugfix
- src/plone/restapi/search/query.py
- src/plone/restapi/tests/__init__.py
- src/plone/restapi/tests/test_search.py
Fixes a regression introduced in https://github.com/plone/plone.restapi/pull/1533
> Fix No such index: 'sort_on' warnings

- news/1563.documentation
- requirements-docs.txt
Refs: https://github.com/plone/documentation/issues/1407
> Pin Sphinx<5,>=3 due to sphinx-book-theme 0.3.3 requirement.

- news/1565.bugfix
- src/plone/restapi/blocks_linkintegrity.py
- src/plone/restapi/tests/test_blocks_linkintegrity.py
Fixes #1565
The linksintegrity retriever should handle the same data formats that are handled by the resolveuid transform.
> Improve blocks linkintegrity retrieval of internal links

- news/1574.bugfix
- src/plone/restapi/serializer/site.py
- src/plone/restapi/tests/http-examples/jwt_logged_in.resp
- src/plone/restapi/tests/http-examples/siteroot.resp
> Fix Plone Site serialization not returning the review_state in Plone 6

- news/4395.bugfix
- src/plone/restapi/services/users/add.py
Fixes https://github.com/plone/volto/issues/4395. The change avoids accidentally converting a message id to a string before it gets translated.
Confirmed this fixes the problem on the user add form in volto:
> Fix translation of user add exceptions

- news/162.internal
- src/plone/restapi/tests/test_functional_auth.py
See https://github.com/plone/plone.app.z3cform/pull/162
Instead of
```
<input id="__ac_password" name="__ac_password"
```
we get:
```
<input class="form-control password-widget required password-field" id="__ac_password" name="__ac_password" type="password" />
```
> Fixed tests in combination with newer plone.app.z3cform.

- .github/workflows/ci.yml
- news/2004.internal
- plone-5.2.x.cfg
- versions.cfg
Python 2.7 and 3.6 are not available on latest.
See broken runs on this PR job:
https://github.com/plone/plone.restapi/actions/runs/4565635527?pr=1608
BTW, for me it would be fine to stop testing with Python 3.6: it is no longer supported by Plone 5.2. But if this PR gets it going for a few more months, then all is well.
> CI: run the tests on Ubuntu 20.04, instead of latest. [7.x.x]

- docs/source/endpoints/querystringsearch.md
- news/1616.feature
- src/plone/restapi/services/querystringsearch/configure.zcml
- src/plone/restapi/services/querystringsearch/get.py
- src/plone/restapi/tests/http-examples/querystringsearch_get.req
- src/plone/restapi/tests/http-examples/querystringsearch_get.resp
- src/plone/restapi/tests/test_documentation.py
- src/plone/restapi/tests/test_services_querystringsearch.py
> Add querystring_search get method

- news/3754.bugfix
- src/plone/restapi/services/email_send/post.py
This could result in missing characters in an email body. See https://github.com/plone/Products.CMFPlone/issues/3754
Cherry-picked from https://github.com/plone/plone.restapi/pull/1607
> Fixed encoding issue on Python 3 for some mail servers. [7.x.x]

- news/1621.bugfix
- src/plone/restapi/services/querystringsearch/get.py
- src/plone/restapi/tests/test_services_querystringsearch.py
Copy the params from the querystring into the request body, because there are too many bits of code that expect to find things there.
Adjusted the test to confirm pagination works.
Fixes #1621
> Fix param handling in querystringsearch GET

- news/140.internal
- plone-4.3.x.cfg
@tisto I wanted to create a release of 7.x.x for the upcoming Plone 5.2 release, but saw the build was broken.  This should fix it.
This `plone.schema` is the latest version compatible with Python 2. On Plone 5.0 and higher this package is already pinned. A Python 3 only version was released on April 6th, and broke the build: https://github.com/plone/plone.restapi/actions/runs/4635281794/jobs/8202199547
```
Traceback (most recent call last):
File "/home/runner/work/plone.restapi/plone.restapi/src/plone/restapi/tests/test_behaviors.py", line 7, in <module>
from plone.restapi.behaviors import IBlocks
File "/home/runner/work/plone.restapi/plone.restapi/src/plone/restapi/behaviors.py", line 4, in <module>
from plone.schema import JSONField
File …
```
> Tests: pin plone.schema to 1.4.0 in Plone 4.3.

- news/1630.bugfix
- src/plone/restapi/services/users/add.py
- src/plone/restapi/tests/test_services_users.py
`p.restapi` is using `PasswordResetTool.resetPassword` for updating passwords, however this method doesn't check for password validity (https://github.com/plone/Products.CMFPlone/blame/master/Products/CMFPlone/PasswordResetTool.py#L103).
This results in Volto bypassing the default password policy. Although the minimum password length has been updated to 8 characters (https://github.com/plone/Products.PlonePAS/pull/69), Volto still mentions a minimum of 5 characters (https://github.com/plone/volto/blob/master/src/components/theme/PasswordReset/PasswordReset.jsx#L54) and Plone lets you get away with this. I actually could use a 3 letter password.
> update_password should check password validity

- news/1644.bugfix
- src/plone/restapi/serializer/controlpanels/configure.zcml
- src/plone/restapi/services/configure.zcml
- src/plone/restapi/services/controlpanels/configure.zcml
- src/plone/restapi/services/rules/configure.zcml
Also: only load code related to contentrules when this package is available.
Fixes https://github.com/plone/plone.restapi/issues/1644
I have a small doubt where some of these conditions should be on `plone.contentrules` instead of `plone.app.contentrules`.  But I guess this is one of those split packages where you either have none or both.  I doubt that anyone has written an own implementation on top of `plone.contentrules` that actually works with the current restapi code around it.  I think we do not need to worry.
> Fix possible startup error by loading plone.app.contentrules zcml

- news/1651.bugfix
- src/plone/restapi/serializer/dxcontent.py
- src/plone/restapi/tests/test_services_history.py
Fixes #1650 
If the item was renamed or moved, then its id might not be found in the current object's container. In that case let's degrade gracefully and leave out the previous_item and next_item rather than raising a ValueError.
> Skip next/previous info for old versions if it can't be obtained

- docs/source/contributing/index.md
- news/1664.documentation
This pull request adds documentation for code formatting and testing in the `plone.restapi` project.
The documentation includes instructions on installing the "black" tool for code formatting, using the `make` command to install project dependencies, and running tests locally.
This pr is related to #1664
> Add Documentation for Code Formatting and Testing

- Makefile
- news/1669.bugfix
- plone-5.2.x.cfg
- requirements-5.2.txt
- src/plone/restapi/services/types/configure.zcml
- src/plone/restapi/services/types/get.py
- src/plone/restapi/tests/test_expansion.py
Related to: https://github.com/plone/volto/pull/4946
The tests failed for 5.2 when trying to use the expander in a non-DX Plone site root.
I updated also the build for 5.2 to latest Plone 5.
> Fix types expander in root for 5.2 (for non-DX Plone Site Root)

- README.rst
- news/1693.documentation
> Fix linkcheckbroken 301 redirect to https://www.4teamwork.ch/en

- docs/source/upgrade-guide.md
- news/1691.documentation
Restores formatting and fixes some MyST syntax from #1689.
I am not sure whether to restore these deleted lines: https://github.com/plone/plone.restapi/pull/1689/files#diff-5181575a5b963d950ad39243e813f929f21691c3698835f2784db8fd692ccd51R710-R722 @tisto @davisagli please advise.
> Formatting fixes for #1689

- news/1.bugfix
- src/plone/restapi/tests/test_batching.py
- src/plone/restapi/tests/test_permissions.py
- src/plone/restapi/tests/test_search.py
- src/plone/restapi/tests/test_serializer_catalog.py
- src/plone/restapi/tests/test_services.py
- src/plone/restapi/tests/test_services_querystring.py
That's part of https://github.com/plone/Products.CMFPlone/issues/3852 effort
> Fix regex asserts

- news/1723.bugfix
- src/plone/restapi/services/multilingual/configure.zcml
- src/plone/restapi/tests/test_translations.py
This fix limits the use of multilingual services only if multilingual is actually installed, not only if it is present tar the 'eggs' (because in the new distribution of Plone, `plone.app.multilingual` is always present).
> fix: use pam layer in pam services

- news/1167.bugfix
- src/plone/restapi/services/users/get.py
- src/plone/restapi/tests/test_services_users.py
This takes over some code from https://github.com/zopefoundation/Zope/pull/1167. See also https://github.com/plone/plone.namedfile/pull/154
> Be more strict when checking if mimetype is allowed inline.

- news/1728.bugfix
- src/plone/restapi/pas/plugin.py
Alternative to #1726 
We should only try to parse the request body as JSON if there's a request header saying it's JSON.
> jwt_auth plugin extractCredentials: check request content-type

- news/3848.bugfix
- src/plone/restapi/__init__.py
- src/plone/restapi/deserializer/__init__.py
- src/plone/restapi/patches.py
This fixes a regression due to a low Zope form memory limit of 1MB used since Plone 6.0.7. You can use ``dos_protection`` settings in ``etc/zope.conf`` to change the limit. See https://github.com/plone/Products.CMFPlone/issues/3848 and https://github.com/zopefoundation/Zope/pull/1142.
> Temporarily disable form memory limit checking for files and images.

- .github/workflows/tests.yml
- news/1732.internal
Plone 5.2 no longer supports Python 3.7. See: https://github.com/plone/Products.CMFPlone/blob/5.2.14/setup.py#L25-L26
> Does not test in Python 3.7

- base.cfg
- news/1733.internal
- src/plone/restapi/tests/http-examples/translated_messages_addons.resp
There are tests that need translation. If we started the instance for testing, the translation files were generated, causing the documentation tests to give a different result locally, since in CI the mo files did not exist.
> Use plone.recipe.precompiler to generate mo files to test

- .github/workflows/tests.yml
- news/1740.internal
Uses Python 3.12.0 in tests, while errors in tests with Python 3.12.1 are not fixed
Tests in 3.12.1 is broken.
Fixes #1740
> Uses Python 3.12.0 in tests

- news/1746.bugfix
- src/plone/restapi/deserializer/utils.py
- src/plone/restapi/serializer/utils.py
- src/plone/restapi/tests/test_blocks_deserializer.py
- src/plone/restapi/tests/test_blocks_serializer.py
Now it covers the use case if an anchor is present.
> Improve the block transforms to include also anchors when resolving uid back and forth

- base.cfg
- news/1734.internal
This setting was causing validation errors to return `BadRequest`. This is different from a normal Plone installation.
It seems like it is a necessary configuration in performance tests. But we already have this configuration in the performance test buildout:
https://github.com/plone/plone.restapi/blob/366a9d0c61b1599032de275520e10c2a8a0925a6/plone-6.0.x-performance.cfg#L9
fixes #1734
> Remove debug-exceptions = on from the buildout instance section

- news/1748.bugfix
- src/plone/restapi/deserializer/utils.py
- src/plone/restapi/serializer/utils.py
- src/plone/restapi/tests/test_blocks_deserializer.py
- src/plone/restapi/tests/test_blocks_serializer.py
@davisagli we overlooked this one :( the roundtrip was bugged because of the trailing slash. Please take a look at the regex, if it's fine like this.
> Fix serializer block with anchors, remove trailing slash before the anchor

- Makefile
- news/1753.bugfix
Issue Description:
The Makefile uses realpath to set **SPHINXBUILD and SPHINXAUTOBUILD**:
```
SPHINXBUILD     = $(realpath bin/sphinx-build)
SPHINXAUTOBUILD = $(realpath bin/sphinx-autobuild)
```
replace with 
```
SPHINXBUILD     = "$(realpath bin/sphinx-build)"
SPHINXAUTOBUILD = "$(realpath bin/sphinx-autobuild)"
```
This can cause compatibility issues and doesn't handle special characters in paths. We need to replace realpath with a more portable and robust method. **This issues was already discussed with @stevepiercy on plone community** [conversation link](https://community.plone.org/t/error-running-training-repo-seek-advice-on-pull-request/18618/8?u=vivek-04022001)
> Enhance Path Handling in Makefile

- news/1750.bugfix
- src/plone/restapi/services/groups/add.py
- src/plone/restapi/services/groups/update.py
- src/plone/restapi/tests/test_services_groups.py
The `addMember` method requires the user to have the `Manage Users` permission but the Site Administrator does not have this permission. Then we use the `addPrincipalToGroup` method, which does not require this permission.
fixes #1750
> Give Site Administrator permission to add users to groups

- news/1758.bugfix
- src/plone/restapi/__init__.py
- src/plone/restapi/imaging.py
The `direction` parameter is deprecated. This avoids the warning:
DeprecationWarning: The 'direction' option is deprecated, use 'mode' instead.
Also change value to `scale`.
Even though we get the warning in Plone 5.2, the tests fail when we use mode. So we keep direction in Plone 5.2.
Ref: https://github.com/plone/Products.CMFPlone/issues/3850
> Use the mode parameter instead of direction when calling the scale method

- .github/workflows/black.yml
- .github/workflows/flake8.yml
- .github/workflows/pyroma.yml
- .github/workflows/tests.yml
- .github/workflows/zpretty.yml
- news/1762.internal
flake8 is not ready for Python 3.12, so it stays at 3.11 for now, unless another tool replaces it.
> Bump all the versions in GitHub workflows

- news/1716.internal
- src/plone/restapi/tests/test_content_get.py
> Test showing the difference

- news/1744.bugfix
- src/plone/restapi/behaviors.py
- src/plone/restapi/indexers.py
- src/plone/restapi/indexers.zcml
- src/plone/restapi/tests/test_blocks_searchable_text.py
- src/plone/restapi/tests/test_indexers.py
This ensures that behaviors can add fields to SearchableText with `plone.textindexer`.
`IBlocks` now inherits from `IDexterityTextIndexer`, so there is no need to add the `plone.textindexer` behavior to the types to enable indexing. The content simply needs to have the `IBlocks` behavior.
fixes #1744
> In Plone 6, uses plone.textindexer to add block texts to the SearchableText index

- news/1772.bugfix
- src/plone/restapi/serializer/blocks.py
- src/plone/restapi/tests/test_blocks_serializer.py
This lead to problems when for example we have a custom service that serialize some blocks and do not force a json_compatible formatting to the returned data.
I have a service that take some blocks, serialize them and return the result.
But image_scales are a PersistentMapping instance and breaks json formatting.
For content-types serialization or other services like @search this is not a problem because there is something that force json compatibility.
> image_scales in serializer are returned as json_compatible format

- news/1775.bugfix
- src/plone/restapi/services/users/get.py
Fixes #1774 
@djay Any chance you can test whether this fixes the error you reported?
> Users service: fix edge case where a userid is returned by search but isn't an actual user

- docs/source/endpoints/comments.md
- news/1781.bugfix
- setup.py
- src/plone/restapi/serializer/configure.zcml
- src/plone/restapi/services/configure.zcml
- src/plone/restapi/testing.py
- src/plone/restapi/tests/statictime.py
- src/plone/restapi/tests/test_statictime.py
- Turn usage/endpoints of plone.app.discussion features into optional features: ZCML conditions and optionla imports.
- Fix tests to pull in plone.app.discussion explicitly
> Support for plone.app.discussion as core add-on

- news/125.bugfix
- src/plone/restapi/services/contextnavigation/get.py
Theoretically we checked `portal_properties.site_properties.sortAttribute`.
> Remove use of `portal_properties` in context navigation.

- news/1799.bugfix
- plone-6.0.x-python3.8.cfg
- plone-6.0.x.cfg
- requirements-6.0.txt
- src/plone/restapi/serializer/nextprev.py
- src/plone/restapi/tests/http-examples/collection.resp
- src/plone/restapi/tests/http-examples/collection_fullobjects.resp
- src/plone/restapi/tests/http-examples/content_get.resp
- src/plone/restapi/tests/http-examples/content_get_folder.resp
- src/plone/restapi/tests/http-examples/content_patch_representation.resp
- src/plone/restapi/tests/http-examples/content_post.resp
- src/plone/restapi/tests/http-examples/event.resp
- src/plone/restapi/tests/http-examples/file.resp
- src/plone/restapi/tests/http-examples/folder.resp
- src/plone/restapi/tests/http-examples/image.resp
- src/plone/restapi/tests/http-examples/link.resp
- src/plone/restapi/tests/http-examples/navroot_lang_content_get.resp
- src/plone/restapi/tests/http-examples/navroot_lang_folder_get.resp
- src/plone/restapi/tests/http-examples/newsitem.resp
- src/plone/restapi/tests/http-examples/search_fullobjects.resp
- src/plone/restapi/tests/http-examples/site_get_expand_lang_folder.resp
- src/plone/restapi/tests/http-examples/site_get_expand_lang_folder_content.resp
- src/plone/restapi/tests/http-examples/translated_messages_types_folder.resp
- src/plone/restapi/tests/http-examples/translations_expand_get.resp
- src/plone/restapi/tests/http-examples/translations_link_on_post.resp
- src/plone/restapi/tests/http-examples/translations_unexpanded_get.resp
- src/plone/restapi/tests/http-examples/workingcopy_baseline_get.resp
- src/plone/restapi/tests/http-examples/workingcopy_wc_get.resp
- src/plone/restapi/tests/test_dxcontent_serializer.py
> Include next/previous only if enabled

- news/244.tests
- src/plone/restapi/tests/test_dxcontent_serializer.py
In Plone 6.1, when you actively activate plone.app.discussion, we may globally enable comments by default. This is when https://github.com/plone/plone.app.discussion/pull/244 gets merged.
We already had eight or so tests that explicitly globally enable comments. Now we explicitly globally disable them in two others. Then the tests work in Plone 6.0 and 6.1.
See two test failures here for the plone.app.discussion PR: https://jenkins.plone.org/job/pull-request-6.1-3.10/311/
----
📚 Documentation preview 📚: https://plonerestapi--1805.org.readthedocs.build/
> Explicitly globally disable comments in the tests that need it.

- news/1808.bugfix
- src/plone/restapi/serializer/dxcontent.py
- src/plone/restapi/tests/http-examples/jwt_logged_in.resp
- src/plone/restapi/tests/http-examples/navroot_site_get.resp
- src/plone/restapi/tests/http-examples/navroot_standard_site_content_get.resp
- src/plone/restapi/tests/http-examples/navroot_standard_site_content_get_expansion.resp
- src/plone/restapi/tests/http-examples/navroot_standard_site_get.resp
- src/plone/restapi/tests/http-examples/navroot_standard_site_get_expansion.resp
- src/plone/restapi/tests/http-examples/site_get_expand_navroot.resp
- src/plone/restapi/tests/http-examples/siteroot.resp
This fixes an error in Plone 6.1 when the `plone.app.discussion` package is available but not activated in the Add-ons. Problem is that the `conversation_view` is only defined when the browser layer of `plone.app.discussion` is found. Traceback:
```
Traceback (innermost last):
Module ZPublisher.WSGIPublisher, line 181, in transaction_pubevents
Module ZPublisher.WSGIPublisher, line 391, in publish_module
Module ZPublisher.WSGIPublisher, line 285, in publish
Module ZPublisher.mapply, line 98, in mapply
Module ZPublisher.WSGIPublisher, line 68, in call_object
Module plone.rest.service, line 21, in __call__
Module plone.restapi.services, line 19, in render
Module plone.restapi.services.content.get, line 16, in reply
Module plone.restapi.serializer.dxcontent, line 179, in __call__
Module …
```
> Fix error getting allow_discussion  when p.a.discussion is not activated.

- docs/source/contributing/index.md
- news/1822.documentation
See https://github.com/plone/documentation/issues/1720
----
📚 Documentation preview 📚: https://plonerestapi--1822.org.readthedocs.build/
> Fix spelling of prerequisites

- news/1818.bugfix
- src/plone/restapi/serializer/relationfield.py
- src/plone/restapi/tests/test_dxcontent_serializer.py
Closes #1745 
Filtered `NoneType` items from the resulting list at `RelationListFieldSerializer`.
I guess we don't need to update this also in `RelationChoiceFieldSerializer`,  as it is returning a single `RelationValue` or `None` value, so it should be fine this way.
----
📚 Documentation preview 📚: https://plonerestapi--1818.org.readthedocs.build/
> Fix invalid values in RelationListFieldSerializer.

- news/1820.bugfix
- src/plone/restapi/services/aliases/configure.zcml
fix for #1820
permissions are taken from https://github.com/plone/Products.CMFPlone/blob/f7f0b19197da7917db154cbb383bede97e1a90a7/Products/CMFPlone/controlpanel/permissions.zcml#L82
----
📚 Documentation preview 📚: https://plonerestapi--1825.org.readthedocs.build/
> Use existing aliases controlpanel permissions for aliases endpoint

- news/1826.feature
- src/plone/restapi/services/site/get.py
- src/plone/restapi/tests/http-examples/site_get.resp
I need this because some new filters were added in CMFPlone for the URL Management control panel, and I want to add support for them in volto, but it needs to check whether it's talking to a backend that supports them.
----
📚 Documentation preview 📚: https://plonerestapi--1826.org.readthedocs.build/
> Add a way to check for backend support of version-dependent features via the site service

- news/1827.bugfix
- src/plone/restapi/configure.zcml
This fixes a `zope.interface.interfaces.ComponentLookupError: (<InterfaceClass zope.security.interfaces.IPermission>, 'Products.CMFPlone.ManagePortalAliases')` which can happen depending on the order in which packages load.
----
📚 Documentation preview 📚: https://plonerestapi--1827.org.readthedocs.build/
> Make sure CMFPlone's permissions are loaded

- news/1828.bugfix
- src/plone/restapi/search/handler.py
- src/plone/restapi/tests/test_search.py
This PR introduces a fix to handle parentheses  in the search functionality.
There is an error when query contains parantheses.
`ParseError
Token <Token:EOF> required, '(' found`
----
📚 Documentation preview 📚: https://plonerestapi--1828.org.readthedocs.build/
> Handle parentheses search queries

- news/1837.bugfix
- src/plone/restapi/services/aliases/add.py
Fixes #1837 
----
📚 Documentation preview 📚: https://plonerestapi--1838.org.readthedocs.build/
> Fix handling of errors in aliases CSV upload

- news/1835.bugfix
- src/plone/restapi/services/users/update.py
- src/plone/restapi/tests/test_services_users.py
Fixes #1835 
----
📚 Documentation preview 📚: https://plonerestapi--1836.org.readthedocs.build/
> Change login name after changing email in sites where "use email as login" is enabled

- news/1840.internal
- src/plone/restapi/services/users/update.py
- src/plone/restapi/tests/test_services_users.py
As a follow-up of #1836, I add additional tests showing that we return an error when trying to change a login to an existing one (see https://github.com/plone/plone.restapi/pull/1836#pullrequestreview-2424965276)
----
📚 Documentation preview 📚: https://plonerestapi--1840.org.readthedocs.build/
> additional tests

- docs/source/conf.py
- news/1846.documentation
- html_use_opensearch value must not have a trailing slash
- Clean up comments
----
📚 Documentation preview 📚: https://plonerestapi--1846.org.readthedocs.build/
> Fix linkcheck

- news/1850.internal
- src/plone/restapi/tests/test_serializer_summary.py
These tests were failing at certain times of day.
----
📚 Documentation preview 📚: https://plonerestapi--1850.org.readthedocs.build/
> fix time-dependence of event recurrent tests

- .github/workflows/tests.yml
- news/1851.bugfix
- src/plone/restapi/serializer/dxcontent.py
- When there is no primary field, do not go through all fields.
- First compare the field name, then the permission: comparing two strings is cheaper.
- If the field name matches, stop iterating over other fields: you have already found the field.
----
📚 Documentation preview 📚: https://plonerestapi--1851.org.readthedocs.build/
> Make primary field target adapter return early.

- news/1848.bugfix
- news/1848.feature
- src/plone/restapi/deserializer/utils.py
- src/plone/restapi/tests/test_blocks_deserializer.py
It's me..again ;)
This time, my edge-case is:
I have a parent Document (/aaa) with some contents inside it (/aaa/foo).
The parent have some text with an internal link to /aaa/foo that is stored in block data as a resolveuid string (correct).
Now, edit parent changing its id (from "aaa" to "bbb") and add some random text.
When you save the form, Volto sends to restapi the blocks with the link to foo like this: http://localhost:3000/aaa/foo.
restapi deserializer now try to resolve all links and convert them in resolveuid-like, but it is called after parent rename, so the path "/aaa/foo" is invalid and lead to store in the parent blocks a link like "http://localhost:3000/aaa/foo" that is potentially broken.
My pr add an additional check in path2uid method, to check also aliases for a given …
> Handle aliases in path2uid

- news/1849.bugfix
- src/plone/restapi/blocks_linkintegrity.py
- src/plone/restapi/deserializer/blocks.py
These are some compatibility fixes when blocks are not proper slate blocks.
We registered some linkintegrity adapters that extends slate one, but in some cases (we have some old installations that does not have slate yet) some methods breaks.
This pr tries to graceful handle them.
----
📚 Documentation preview 📚: https://plonerestapi--1849.org.readthedocs.build/
> Do not break slate linkintegrity if block is not a slate block

- news/1855.bugfix
- src/plone/restapi/batching.py
- src/plone/restapi/services/navigation/get.py
- src/plone/restapi/tests/test_batching.py
- src/plone/restapi/tests/test_services_navigation.py
useful so it can be more easily ignored
----
📚 Documentation preview 📚: https://plonerestapi--1855.org.readthedocs.build/
> Handle bad input as BadRequest instead of ValueError

- .github/workflows/tests.yml
- news/1685.internal
- plone-6.0.x-python3.8.cfg
- plone-6.0.x.cfg
- plone-6.1.x.cfg
- requirements-6.0.txt
- requirements-6.1.txt
- src/plone/restapi/tests/http-examples/registry_get_list.resp
- src/plone/restapi/tests/http-examples/site_get.resp
There was a new release of twine today which requires packaging 24.0, which is not in our KGS. /cc @mauritsvanrees 
----
📚 Documentation preview 📚: https://plonerestapi--1865.org.readthedocs.build/
> Update Plone test versions, and pin twine

- news/1864.bugfix
- src/plone/restapi/services/contextnavigation/get.py
- src/plone/restapi/tests/test_services_contextnavigation.py
Fix the context navigation bug that occurs when a file type is unknown.
In my case, the file had a content type of `application/pkcs7` when I encountered the bug
----
📚 Documentation preview 📚: https://plonerestapi--1864.org.readthedocs.build/
> fix: contextnavigation when a file has an unknown type

- news/1823.feature
- src/plone/restapi/serializer/dxcontent.py
- src/plone/restapi/serializer/site.py
- src/plone/restapi/services/workingcopy/configure.zcml
This is part of: https://github.com/plone/volto/issues/5284
Allows working copy services to be accessed in the Portal. Also returns working copy data in the Portal serialization.
In Plone 6.0, this PR should be tested together with the following PRs:
https://github.com/plone/plone.app.iterate/pull/128
https://github.com/plone/Products.CMFEditions/pull/113
In Plone 6.1, the `plone.app.iterate` PR should be replaced with:
https://github.com/plone/plone.app.iterate/pull/130
----
📚 Documentation preview 📚: https://plonerestapi--1823.org.readthedocs.build/
> Allows working copy of the Portal

- news/1879.bugfix
- src/plone/restapi/search/handler.py
Fixes #1879.
This fix is both backward compatible, and forward compatible with https://github.com/plone/Products.CMFPlone/pull/4099
See also https://github.com/plone/Products.CMFPlone/issues/4098
> Do not hardcode show_inactive in search

- news/1886.feature
- src/plone/restapi/deserializer/blocks.py
- src/plone/restapi/serializer/blocks.py
- src/plone/restapi/tests/dxtypes.py
- src/plone/restapi/tests/test_dxfield_deserializer.py
- src/plone/restapi/tests/test_dxfield_serializer.py
Fixes #1842 
This makes it possible to use a non-blocks JSONField that stores internal links as resolveuid URLs.
----
📚 Documentation preview 📚: https://plonerestapi--1886.org.readthedocs.build/
> Apply the resolveuid transform to all JSON fields, not only blocks

- Makefile
- docs/source/endpoints/index.md
- docs/source/endpoints/inherit.md
- docs/source/usage/expansion.md
- news/1887.feature
- src/plone/restapi/interfaces.py
- src/plone/restapi/serializer/configure.zcml
- src/plone/restapi/serializer/dxcontent.py
- src/plone/restapi/serializer/schema.py
- src/plone/restapi/serializer/site.py
- src/plone/restapi/services/configure.zcml
- src/plone/restapi/services/inherit/configure.zcml
- src/plone/restapi/services/inherit/get.py
- src/plone/restapi/tests/http-examples/inherit.get.req
- src/plone/restapi/tests/http-examples/inherit_expansion.req
- src/plone/restapi/tests/http-examples/inherit_expansion.resp
- src/plone/restapi/tests/http-examples/inherit_get.req
- src/plone/restapi/tests/http-examples/inherit_get.resp
- src/plone/restapi/tests/test_documentation.py
This adds a new service, `@inherit`, to explicitly get values from behaviors assigned to ancestors in the object hierarchy.
(It's Acquisition, but without the bad magic.)
----
📚 Documentation preview 📚: https://plonerestapi--1887.org.readthedocs.build/en/1887/endpoints/inherit.html
> Add `@inherit` service to get inherited behavior values

- news/1890.bugfix
- pyproject.toml
This is needed in order to build a wheel with dist-info named plone.restapi-9.13.1.dev0.dist-info instead of plone_restapi-9.13.1.dev0.dist-info, so that it can be found by older versions of buildout and setuptools.
----
📚 Documentation preview 📚: https://plonerestapi--1890.org.readthedocs.build/
> pin setuptools for build

- news/1916.bugfix
- src/plone/restapi/deserializer/dxcontent.py
- src/plone/restapi/serializer/dxcontent.py
- src/plone/restapi/serializer/schema.py
- src/plone/restapi/serializer/site.py
- src/plone/restapi/services/inherit/get.py
- src/plone/restapi/tests/test_dxcontent_serializer.py
Env:
Plone == 6.1.1
Python == 3.12.8
plone.restapi == 9.13.3
Issue: Exposing of protected information
Reproduce:
Protect any field with a permission not given to an anonymous user
Make request with Manager account, which has the permission --> Field is in response
Make a request as an anonymous user to same object, WITHOUT the permission --> Field is still there!!
Reboot the instance and make a new request as an anonymous user. --> Field is gone.
I'm not sure if this is intentional, or not.
But in my case, it exposes information I don't want to.
It got implemented here: [Add `@inherit` service to get inherited behavior values (#1887) · plone/plone.restapi@763ce18 · GitHub](https://github.com/plone/plone.restapi/commit/763ce189400c4640f7b05ebbc1c3ffcefd5c7eae#diff-74ad4dd30dcaee75ebfef37954 …
> Fix permission check in schema serializer

- news/1917.bugfix
- src/plone/restapi/deserializer/utils.py
- src/plone/restapi/tests/test_services_types.py
- src/plone/restapi/types/utils.py
fixes #1914 
Pass root context when no DX content available on updating field through DX controlpanel.
----
📚 Documentation preview 📚: https://plonerestapi--1917.org.readthedocs.build/
> fix(types/utils): pass root context when no DX content in layout

- news/1913.bugfix
- src/plone/restapi/serializer/atfields.py
Fixes https://github.com/plone/plone.restapi/issues/1913
> Fix error serializing empty reference from Archetypes content. [7.x.x]

- news/+nextprev.feature
- src/plone/restapi/serializer/nextprev.py
(Depends on https://github.com/plone/plone.app.dexterity/pull/409, but falls back to the old serialization without it.)
> Include all summary fields when serializing `next_item` and `previous_item`.
