plone/plone.restapi

.gitignore
src/plone/restapi/serializer/__init__.py
src/plone/restapi/tests/dxtypes.py
src/plone/restapi/tests/test_serializer.py

Serializer, Check read permission

---

src/plone/restapi/services/content/add.py
src/plone/restapi/services/content/configure.zcml
src/plone/restapi/services/content/get.py
src/plone/restapi/services/content/update.py
src/plone/restapi/tests/test_content_delete.py

Requires https://github.com/plone/plone.rest/pull/47

Declare permissions

---

src/plone/restapi/deserializer/configure.zcml
src/plone/restapi/deserializer/dxfields.py
src/plone/restapi/deserializer/relationfield.py
src/plone/restapi/serializer/configure.zcml
src/plone/restapi/serializer/converters.py
src/plone/restapi/serializer/relationfield.py

Ensures compatibility with vanilla Plone 4.3

Make relationfield serializer/deserializer optional

---

docs/source/_json/workflow_get.json
docs/source/_json/workflow_post.json
docs/source/index.rst
docs/source/workflow.rst
src/plone/restapi/services/configure.zcml
src/plone/restapi/services/workflow/configure.zcml
src/plone/restapi/services/workflow/info.py
src/plone/restapi/services/workflow/transition.py
src/plone/restapi/tests/test_documentation.py
src/plone/restapi/tests/test_workflow.py

- `GET /:path/workflow` (get workflow info)
- `POST /:path/workflow/:transition` (trigger workflow transition)

Implement workflow endpoint

---

README.rst
docs/source/crud.rst
docs/source/customization.rst
docs/source/glossary.rst
docs/source/http-status-codes.rst
docs/source/index.rst
docs/source/introduction.rst

changed to a glossary for http status codes, and an extra one for terms (containing just one for now)
also readability updates for index.rst

use glossaries

---

src/plone/restapi/services/registry/update.py
src/plone/restapi/services/workflow/transition.py

I am not completely sure about this pull-request because I don't think I understand correctly the whole CSRF thing, but I see that in the default content-creation service the CSRF check is done, and if I don't do the check to the workflow service too, I can't get the workflow updated.

CSRF Fixes

---

CHANGES.rst
src/plone/restapi/tests/test_types.py
src/plone/restapi/types/adapters.py
src/plone/restapi/types/configure.zcml

- add `required` and `widget` attributes
- support RichText field

Improve @types

---

CHANGES.rst
docs/source/_json/collection.json
docs/source/_json/document.json
docs/source/_json/event.json
docs/source/_json/file.json
docs/source/_json/folder.json
docs/source/_json/image.json
docs/source/_json/link.json
docs/source/_json/newsitem.json
src/plone/restapi/serializer/atcontent.py
src/plone/restapi/serializer/dxcontent.py
src/plone/restapi/tests/test_atcontent_serializer.py
src/plone/restapi/tests/test_dxcontent_serializer.py

This is related to https://github.com/plone/plone.restapi/issues/128

Include 'id' attribute in responses.

---

README.rst

Fix spelling

---

CHANGES.rst
docs/source/authentication.rst
src/plone/restapi/services/__init__.py
src/plone/restapi/services/auth/login.py
src/plone/restapi/tests/test_auth.py

Make login endpoint accessible without UseRESTAPI permission

---

CHANGES.rst
src/plone/restapi/setuphandlers.py

Allow installation of plone.restapi if JWT plugin already exists

---

CHANGES.rst
docs/source/_json/groups.json
docs/source/_json/groups_created.json
docs/source/_json/groups_delete.json
docs/source/_json/groups_filtered_by_groupname.json
docs/source/_json/groups_get.json
docs/source/_json/groups_update.json
docs/source/groups.rst
src/plone/restapi/serializer/configure.zcml
src/plone/restapi/serializer/group.py
src/plone/restapi/services/configure.zcml
src/plone/restapi/services/groups/add.py
src/plone/restapi/services/groups/configure.zcml
src/plone/restapi/services/groups/delete.py
src/plone/restapi/services/groups/get.py
src/plone/restapi/services/groups/update.py
src/plone/restapi/tests/test_documentation.py
src/plone/restapi/tests/test_serializer_group.py
src/plone/restapi/tests/test_services_groups.py

This is the implementation of the @groups endpoints allowing to make CRUD operations. Very much the same as the @users endpoints.

@groups endpoints implementation

---

CHANGES.rst
src/plone/restapi/services/types/get.py
src/plone/restapi/tests/test_services_types.py

Fix @types endpoint non addable types for member users and local roles

---

CHANGES.rst
src/plone/restapi/services/copymove/copymove.py
src/plone/restapi/tests/test_copymove.py

Handle special case when user @move content that cannot delete.

---

CHANGES.rst
docs/source/_json/registry_get_list.req
docs/source/_json/registry_get_list.resp
docs/source/registry.rst
src/plone/restapi/serializer/configure.zcml
src/plone/restapi/serializer/registry.py
src/plone/restapi/services/registry/get.py
src/plone/restapi/tests/test_documentation.py
src/plone/restapi/tests/test_registry.py
src/plone/restapi/tests/test_registry_serializer.py

Add batched listing to `@registry` endpoint

---

CHANGES.rst
docs/source/_json/sharing_folder_get.resp
src/plone/restapi/serializer/local_roles.py
src/plone/restapi/tests/test_content_local_roles.py

inherit flag equals to 'not \_\_ac_local_roles_block__'

Fix the inhirit flag

---

CHANGES.rst
docs/source/_json/registry_get_list.resp
src/plone/restapi/serializer/registry.py
src/plone/restapi/tests/test_registry_serializer.py
src/plone/restapi/types/adapters.py
src/plone/restapi/types/configure.zcml

This allows frontend developers to implement a full registry interface

Add schema to registry listing

---

CHANGES.rst
docs/source/_json/vocabularies.resp
src/plone/restapi/deserializer/dxfields.py
src/plone/restapi/testing.zcml
src/plone/restapi/tests/dxtypes.py
src/plone/restapi/tests/test_atcollection.py
src/plone/restapi/tests/test_dxfield_deserializer.py

Bind schema field to context. Fixes #359

---

CHANGES.rst
docs/source/_json/document.resp
docs/source/_json/newsitem.resp
src/plone/restapi/serializer/atfields.py
src/plone/restapi/serializer/converters.py
src/plone/restapi/tests/test_atfield_serializer.py
src/plone/restapi/tests/test_serializer.py
src/plone/restapi/tests/test_services.py

Richtext serializers return transformed html

---

CHANGES.rst
README.rst

primarily to correct the POST example for creating a new document

some tweaks

---

CHANGES.rst
docs/source/searching.rst
src/plone/restapi/search/handler.py
src/plone/restapi/serializer/catalog.py
src/plone/restapi/tests/test_search.py

Search full objects retrieval

---

CHANGES.rst
docs/source/_json/types.resp
src/plone/restapi/services/types/get.py
src/plone/restapi/tests/test_services_types.py

Filter out non-DX types

---

CHANGES.rst
docs/source/content.rst
src/plone/restapi/deserializer/configure.zcml
src/plone/restapi/deserializer/mixins.py
src/plone/restapi/deserializer/site.py
src/plone/restapi/services/content/configure.zcml
src/plone/restapi/tests/mixin_ordering.py
src/plone/restapi/tests/test_atcontent_deserializer.py
src/plone/restapi/tests/test_dxcontent_deserializer.py
src/plone/restapi/tests/test_site_deserializer.py

This PR allows for content reordering in the site root as wel as setting the layout.
The latter is just a happy coincidence :)

Site root reordering + set layout

---

docs/source/_json/lock_update.req
docs/source/_json/lock_update.resp
docs/source/locking.rst
src/plone/restapi/tests/test_documentation.py

@tisto I've added an example how to update locked objects.

Add documentation about updating locked objects

---

CHANGES.rst
src/plone/restapi/serializer/atcollection.py
src/plone/restapi/serializer/atcontent.py
src/plone/restapi/serializer/collection.py
src/plone/restapi/serializer/dxcontent.py
src/plone/restapi/tests/test_search.py

Fix #381 fullobjects search must return actual content @id

---

CHANGES.rst
src/plone/restapi/deserializer/configure.zcml
src/plone/restapi/deserializer/dxfields.py
src/plone/restapi/tests/test_dxcontent_deserializer.py
src/plone/restapi/tests/test_dxfield_deserializer.py

Fixes #351 for the proved sample.
See also #402

Add deserializer for textline to enforce validation and sanitation

---

docs/source/content.rst

This should solve the TODO to add the implementation link for the add content.

Add implementation link to content.rst

---

CHANGES.rst
src/plone/restapi/tests/test_types.py
src/plone/restapi/types/utils.py

Make @types/[type] work for non-dx types

---

CHANGES.rst
docs/source/_json/users_anonymous.req
docs/source/_json/users_anonymous.resp
docs/source/_json/users_anonymous_get.req
docs/source/_json/users_anonymous_get.resp
docs/source/_json/users_authorized_get.req
docs/source/_json/users_authorized_get.resp
docs/source/_json/users_unauthorized.req
docs/source/_json/users_unauthorized.resp
docs/source/_json/users_unauthorized_get.req
docs/source/_json/users_unauthorized_get.resp
docs/source/users.rst
src/plone/restapi/services/users/configure.zcml
src/plone/restapi/services/users/get.py
src/plone/restapi/tests/test_documentation.py
src/plone/restapi/tests/test_services_users.py

Allow each user to get his own information

---

CHANGES.rst
src/plone/restapi/serializer/atcontent.py
src/plone/restapi/tests/test_search.py
src/plone/restapi/tests/test_serializer_catalog.py

Fix the use of fullobjects in Archetypes based sites @search

---

CHANGES.rst
docs/source/_json/workflow_post_with_body.req
docs/source/_json/workflow_post_with_body.resp
docs/source/workflow.rst
src/plone/restapi/services/workflow/transition.py
src/plone/restapi/tests/test_documentation.py
src/plone/restapi/tests/test_workflow.py

- Support applying transitions for all contained items.
- Support setting effective and expiration dates.
Fixes #333

Workflow enhancements

---

CHANGES.rst
docs/source/_json/translated_messages_object_history.req
docs/source/_json/translated_messages_object_history.resp
docs/source/_json/translated_messages_object_workflow.req
docs/source/_json/translated_messages_object_workflow.resp
docs/source/_json/translated_messages_types.req
docs/source/_json/translated_messages_types.resp
docs/source/_json/translated_messages_types_folder.req
docs/source/_json/translated_messages_types_folder.resp
docs/source/i18n.rst
docs/source/index.rst
src/plone/restapi/tests/test_documentation.py

document the use of the Accept-Language header

---

src/plone/restapi/tests/test_tus.py

See https://github.com/plone/plone.restapi/issues/552

Cleanup TUS-tests (to avoid test failure on 5.2) 

---

CHANGES.rst
src/plone/restapi/setuphandlers.py

Avoid AttributeError on add-on installation

---

CHANGES.rst
src/plone/restapi/services/email_notification/post.py
src/plone/restapi/tests/test_services_email_notification.py

Errors had a different data structure than the other endpoints

Standardize errors data structure of email-notification endpoint

---

news/688.bugfix
setup.py

See https://www.python.org/dev/peps/pep-0508/#environment-markers

use environment-markers instead of python-logic

---

news/676.bugfix
src/plone/restapi/services/workflow/transition.py
src/plone/restapi/testing.py

Python 3 incompatibility fixed

Fix for #676 in workflow service.

---

news/700.bugfix
src/plone/restapi/setuphandlers.py

Fixes https://github.com/plone/plone.restapi/issues/700

Hide performance, testing, and tiles profile.

---

docs/source/upgrade-guide.rst

We have to include if we make any change to the args names that we talked this morning.

Suggestions for the upgrade guide

---

docs/source/upgrade-guide.rst
news/691.breaking
news/726.breaking
src/plone/restapi/deserializer/dxfields.py
src/plone/restapi/serializer/dxfields.py
src/plone/restapi/tests/http-examples/collection.resp
src/plone/restapi/tests/http-examples/controlpanels_get_item.resp
src/plone/restapi/tests/test_dxfield_deserializer.py
src/plone/restapi/tests/test_dxfield_serializer.py

Return the token and the title of vocabulary terms in serialization

---

news/738.bugfix
src/plone/restapi/deserializer/relationfield.py
src/plone/restapi/tests/test_dxfield_deserializer.py

Return an error message if a referenced object can not be resolved

---

docs/source/serialization.rst
news/732.bugfix

Improve documentation for how to set relations

---

base.cfg
news/769.feature

Add omelette to the buildout

---

news/775.bugfix
src/plone/restapi/services/__init__.py
src/plone/restapi/services/content/delete.py
src/plone/restapi/services/content/sharing.py
src/plone/restapi/services/content/tus.py
src/plone/restapi/services/content/update.py
src/plone/restapi/services/controlpanels/patch.py
src/plone/restapi/services/discussion/conversation.py
src/plone/restapi/services/email_notification/post.py
src/plone/restapi/services/email_send/post.py
src/plone/restapi/services/groups/delete.py
src/plone/restapi/services/groups/update.py
src/plone/restapi/services/multilingual/pam.py
src/plone/restapi/services/registry/update.py
src/plone/restapi/services/users/delete.py
src/plone/restapi/services/users/update.py

Fix 204 no content

---

docs/source/expansion.rst
news/766.feature
src/plone/restapi/services/types/configure.zcml
src/plone/restapi/services/types/get.py
src/plone/restapi/tests/http-examples/collection.resp
src/plone/restapi/tests/http-examples/content_get.resp
src/plone/restapi/tests/http-examples/content_patch_representation.resp
src/plone/restapi/tests/http-examples/content_post.resp
src/plone/restapi/tests/http-examples/document.resp
src/plone/restapi/tests/http-examples/event.resp
src/plone/restapi/tests/http-examples/expansion.resp
src/plone/restapi/tests/http-examples/expansion_expanded.resp
src/plone/restapi/tests/http-examples/expansion_expanded_full.req
src/plone/restapi/tests/http-examples/expansion_expanded_full.resp
src/plone/restapi/tests/http-examples/file.resp
src/plone/restapi/tests/http-examples/folder.resp
src/plone/restapi/tests/http-examples/image.resp
src/plone/restapi/tests/http-examples/link.resp
src/plone/restapi/tests/http-examples/newsitem.resp
src/plone/restapi/tests/http-examples/search_fullobjects.resp
src/plone/restapi/tests/test_documentation.py
src/plone/restapi/tests/test_expansion.py

Make `@types` endpoint expandable.
Fixes #766

Make @types endpoint expandable.

---

news/690.bugfix
src/plone/restapi/deserializer/atfields.py
src/plone/restapi/deserializer/configure.zcml
src/plone/restapi/serializer/atfields.py
src/plone/restapi/serializer/configure.zcml

Fixed startup error with Archetypes but without p.a.blob/collection

---

news/698.feature
src/plone/restapi/serializer/atcollection.py
src/plone/restapi/tests/test_atcollection.py

implement ?fullobjects support for AT collections

---

docs/source/plone-content.rst
news/848.feature
src/plone/restapi/serializer/collection.py
src/plone/restapi/tests/http-examples/collection_fullobjects.req
src/plone/restapi/tests/http-examples/collection_fullobjects.resp
src/plone/restapi/tests/test_documentation.py
src/plone/restapi/tests/test_serializer.py

Implement ?fullobjects support for DX collections

---

docs/source/translations.rst
news/645.feature
src/plone/restapi/services/multilingual/pam.py
src/plone/restapi/tests/http-examples/translations_post_by_id.req
src/plone/restapi/tests/http-examples/translations_post_by_id.resp
src/plone/restapi/tests/http-examples/translations_post_by_uid.req
src/plone/restapi/tests/http-examples/translations_post_by_uid.resp
src/plone/restapi/tests/test_documentation.py
src/plone/restapi/tests/test_translations.py

Allow objects paths and UIDs to link translations.

---

news/886.feature
src/plone/restapi/interfaces.py
src/plone/restapi/serializer/configure.zcml
src/plone/restapi/serializer/dxcontent.py
src/plone/restapi/serializer/dxfields.py
src/plone/restapi/testing.zcml
src/plone/restapi/tests/dxtypes.py
src/plone/restapi/tests/test_dxcontent_serializer.py

https://github.com/plone/plone.restapi/issues/886

[WIP] dxcontent: add targetUrl for primary file fields

---

docs/source/searching.rst

Add note about metadata.

---

news/917.bugfix
src/plone/restapi/upgrades/ordering.py

remove the use of plone.api in upgrade code

---

news/963.bugfix
src/plone/restapi/serializer/configure.zcml
src/plone/restapi/serializer/converters.py
src/plone/restapi/tests/test_dxcontent_serializer.py
src/plone/restapi/tests/test_dxfield_deserializer.py
src/plone/restapi/tests/test_dxfield_serializer.py

Add a converter for Decimal() objects.

---

news/875.feature
src/plone/restapi/services/copymove/copymove.py
src/plone/restapi/services/multilingual/pam.py

Remove uneeded stringtype checks

---

.gitignore
.travis.yml
news/1012.bugfix
plone-5.2.x.cfg

Fix tests in Travis

---

news/1012.bugfix

CI fixs should not be in changelog.

Remove changelog entry 1012.bugfix

---

plone-4.3.x.cfg

Uses Plone 4.3.20 in tests

---

news/2024.bugfix
src/plone/restapi/tests/test_search.py
src/plone/restapi/tests/test_serializer_summary.py

see  https://github.com/plone/Products.CMFPlone/pull/3208

Prepare to work without unused meta_type index

---

.gitignore
plone-5.1.x.cfg
versions.cfg

This also fixes the Plone 5.1 build.

Uses Plone 5.1.7 in tests

---

news/1029.bugfix
src/plone/restapi/services/content/add.py

See #1029 for reference
@libargutxi

Check that we are in Plone 5 in content-adding endpoint if p.a.multilingual is installed

---

docs/source/upgrade-guide.rst
news/1047.feature
src/plone/restapi/services/navigation/get.py
src/plone/restapi/tests/http-examples/expansion_expanded_full.resp
src/plone/restapi/tests/http-examples/navigation.resp
src/plone/restapi/tests/http-examples/navigation_tree.resp
src/plone/restapi/tests/http-examples/translated_messages_types_folder.resp
src/plone/restapi/tests/test_expansion.py
src/plone/restapi/tests/test_services_navigation.py

Includes the new nav_title attribute

Refactor navigation endpoint

---

news/1058.bugfix
src/plone/restapi/deserializer/blocks.py
src/plone/restapi/serializer/blocks.py
src/plone/restapi/tests/test_blocks_deserializer.py
src/plone/restapi/tests/test_blocks_serializer.py

Since the href field is in the "@id" key...

Fix transform object_browser href smartfield not working as expected

---

news/1061.bugfix
src/plone/restapi/services/navigation/get.py

@cekk My bad, sorry for the hassle! :P

Remove escape from @navigation endpoint

---

news/1068.feature
news/1072.feature
src/plone/restapi/configure.zcml
src/plone/restapi/meta.zcml
src/plone/restapi/tests/test_blocks_deserializer.py

I want to be able to:
```
<configure zcml:condition="has plonerestapi7">
...
```
Added a couple of comprehensive tests for feature reassurance too.

Mark restapi 7 with a zcml feature flag

---

news/1073.bugfix
src/plone/restapi/types/utils.py

Avoid duplicate fields from multiple behaviors

---

news/1083.bugfix
src/plone/restapi/tests/test_blocks_deserializer.py
src/plone/restapi/tests/test_blocks_serializer.py

Add GSM unsubscribe for test registered adapters

---

docs/source/blocks.rst
news/1085.feature
src/plone/restapi/deserializer/blocks.py
src/plone/restapi/serializer/blocks.py
src/plone/restapi/tests/test_blocks_deserializer.py
src/plone/restapi/tests/test_blocks_serializer.py

Fixes https://github.com/plone/plone.restapi/issues/1084

Add subblocks transformer support

---

news/1103.bugfix
src/plone/restapi/types/adapters.py

Sorry, JS keeps trying to poison my Python.

Fixes if old p.schema is used

---

news/1123.bugfix
plone-4.3.x.cfg

Fix Plone 4 build

---

news/1129.bugfix
src/plone/restapi/services/workflow/utils.py

Update import to fix a deprecation warning

---

news/1129.bugfix
src/plone/restapi/services/workflow/utils.py

[7.x] Update import to fix a deprecation warning

---

src/plone/restapi/tests/test_batching.py

This is a cherry pick of  #1127 for banch 7.x .

Fix intermittent failures in test_batching

---

news/1107.bugfix
src/plone/restapi/services/navigation/get.py
src/plone/restapi/tests/test_services_navigation.py

Ref. https://github.com/plone/plone.restapi/issues/1107, modified the base query to fix sorting.

#1107 Fix navigation endpoint sort

---

src/plone/restapi/tests/test_services_navigation.py

In fact this is unrelated to the merges. *shrug*

Fix black after two merges

---

news/1159.bugfix
src/plone/restapi/types/adapters.py

cleaned up #1160 after messing with rebasing
fix #1159

Fix bug: Provide value_type of plone.schema / zope.schema Dict field

---

docs/source/batching.rst

Corrected the spelling of resultset

Minor typo corrected

---

news/1169.bugfix
src/plone/restapi/profiles/testing/catalog.xml
src/plone/restapi/services/navigation/get.py
src/plone/restapi/tests/dxtypes.py
src/plone/restapi/tests/http-examples/link.resp
src/plone/restapi/tests/test_services_navigation.py

Fix nav_title metadata not being applied on navigation service items.

---

news/1107.bugfix
src/plone/restapi/services/navigation/get.py
src/plone/restapi/tests/test_services_navigation.py

* #1107 Fix navigation endpoint sort

Backport #1145 pull request to 7.x.x branch

---

CONTRIBUTORS.rst

- https://github.com/plone/plone.restapi/graphs/contributors

Upgrade CONTRIBUTORS according to:

---

news/1199.bugfix
src/plone/restapi/services/users/get.py

@users endpoint should use acl_users.searchUsers.

---

news/1211.feature
src/plone/restapi/deserializer/dxcontent.py
src/plone/restapi/tests/test_search.py

in DX DeserializFromJson. Refs #1211

Make masking specific validation errors configurable 

---

base.cfg
news/1256.bugfix

Change the checkout of a not existing branch to master

---

news/1269.bugfix
src/plone/restapi/configure.zcml
src/plone/restapi/setuphandlers.py

For some reason i did not get the JWT plugin installed with the default profile. While looking at it I modernized the GS calls and now it works.

fix: pas plugin was missing after install

---

news/1271.bugfix
src/plone/restapi/tests/http-examples/translated_messages_types_folder.resp
src/plone/restapi/tests/http-examples/types_document.resp
src/plone/restapi/tests/http-examples/types_document_put.req
src/plone/restapi/types/utils.py

Fix schema generation when /@types/ is used in a context

---

plone-4.3.x.cfg
plone-5.1.x.cfg
versions.cfg

Fix: https://github.com/plone/plone.restapi/actions/runs/1500046066

Fix buildout in Plone 5.1 and 4.3

---

plone-5.2.x.cfg
requirements.txt

Use Plone 5.2.6 in tests

---

news/1289.bugfix
src/plone/restapi/deserializer/dxcontent.py
src/plone/restapi/tests/dxtypes.py
src/plone/restapi/tests/test_dxcontent_deserializer.py
src/plone/restapi/tests/test_dxcontent_serializer.py

Reverts plone/plone.restapi#1283

Revert "Improve support for `missing_value` and `default` story"

---

docs/source/blocks.rst
news/1292.bugfix
src/plone/restapi/indexers.py
src/plone/restapi/indexers.zcml
src/plone/restapi/tests/test_blocks_searchable_text.py
src/plone/restapi/tests/test_indexers.py

Keep order of blocks when indexing SearchableText

---

news/1332.bugfix
src/plone/restapi/services/multilingual/pam.py
src/plone/restapi/tests/test_translations.py

complementary to the previous PR.

Restrict unlinking on Language Root Folders

---

news/1335.bugfix
src/plone/restapi/serializer/atcontent.py

Fix serializing revisions of AT content

---

src/plone/restapi/tests/test_dxfield_serializer.py
src/plone/restapi/tests/test_serializer.py

see plone/Products.CMFPlone#3279

Plip #3279

---

README.rst
news/1351.bugfix

See https://github.com/plone/plone.restapi/pull/1337#pullrequestreview-929571301

Use /en as the default redirect

---

docs/source/controlpanels.md
docs/source/translations.md
news/1380.bugfix

Control panels and translations are supported in Plone 5 or greater

---

news/1193.bugfix
setup.py
src/plone/restapi/pas/plugin.py

Takes code from https://github.com/plone/plone.restapi/pull/1194
Fixes https://github.com/plone/plone.restapi/issues/1193

Make the PAS plugin compatible with PyJWT 1 and 2.

---

.github/workflows/black.yml
news/1211.feature
plone-4.3.x.cfg
plone-5.1.x.cfg
src/plone/restapi/deserializer/dxcontent.py
src/plone/restapi/serializer/atcontent.py
versions.cfg

Make masking specific validation errors configurable in DX DeserializeFromJson.

Backport 1211 to 7.x.x

---

news/1365.feature
src/plone/restapi/serializer/dxfields.py

Better term lookup error logging

---

docs/source/controlpanels.md
news/1396.bugfix
src/plone/restapi/tests/http-examples/controlpanels_patch.resp

[docs] Fix inconsistency for PATCH controlpanel HTTP response

---

news/1393.feature
src/plone/restapi/services/aliases/add.py
src/plone/restapi/services/aliases/configure.zcml
src/plone/restapi/services/aliases/delete.py
src/plone/restapi/services/aliases/get.py

@aliases Root endpoints

---

docs/source/i18n.md
news/1412.bugfix
src/plone/restapi/services/addons/addons.py
src/plone/restapi/tests/http-examples/translated_messages_addons.req
src/plone/restapi/tests/http-examples/translated_messages_addons.resp
src/plone/restapi/tests/test_documentation.py

translate addon titles in @addon endpoint 

---

news/1424.feature
src/plone/restapi/services/groups/update.py
src/plone/restapi/tests/http-examples/groups_update.req
src/plone/restapi/tests/test_documentation.py

fix https://github.com/plone/plone.restapi/issues/1424

"Update group": Preserve title and description when no values given

---

news/1436.feature
src/plone/restapi/controlpanels/registry.py
src/plone/restapi/services/controlpanels/configure.zcml
src/plone/restapi/tests/http-examples/controlpanels_get.resp

Add UsersGroupsSettings to set of control panels.

---

docs/source/users.md
news/1443.feature
src/plone/restapi/services/users/get.py
src/plone/restapi/tests/http-examples/translated_messages_addons.resp
src/plone/restapi/tests/http-examples/users_searched.req
src/plone/restapi/tests/http-examples/users_searched.resp
src/plone/restapi/tests/test_documentation.py

The change is backward compatible: `?query=` works like before: query for username.
I corrected the documentation for `?query=` : it queries and queried already in username not only startswith!
fix https://github.com/plone/plone.restapi/issues/1443

@users: Support search for fullname, email, id with `?search=`

---

news/169.bugfix
src/plone/restapi/profiles/testing/types/DXTestDocument.xml
src/plone/restapi/testing.zcml
src/plone/restapi/tests/http-examples/controlpanels_get_dexterity_item.resp
src/plone/restapi/tests/http-examples/controlpanels_post_dexterity_item.resp

The 'name' property may become required.
See https://github.com/plone/plone.dexterity/issues/169

Tests: add names to behaviors.

---

docs/source/conf.py
news/1459.bugfix
src/plone/restapi/services/users/get.py
src/plone/restapi/tests/http-examples/translated_messages_addons.resp
src/plone/restapi/tests/http-examples/workingcopy_baseline_get.resp

acl_users.searchUsers fails for id=None
Fix https://github.com/plone/plone.restapi/issues/1459

Fix of users endpoint for Membrane users.

---

docs/source/content.md
news/1430.bugfix

as described in the issue #1430

Fixed basic documentations for 404 error (Issue #1430)

---

news/1189.bugfix
src/plone/restapi/services/registry/get.py

@registry Endpoint datetime not serializable fix

---

news/1449.bugfix
src/plone/restapi/serializer/blocks.py
src/plone/restapi/serializer/site.py
src/plone/restapi/serializer/utils.py

Fixes #1449 
cc: @ionlizarazu @libargutxi

handle subblocks in IPloneSiteRoot in Plone 5.2

---

news/1482.bugfix
src/plone/restapi/controlpanels/registry.py
src/plone/restapi/tests/http-examples/translated_messages_addons.resp

Fix the category of the 'Users and groups settings' controlpanel adapter

---

docs/source/portrait.md
news/1480.feature
src/plone/restapi/serializer/user.py
src/plone/restapi/services/users/configure.zcml
src/plone/restapi/services/users/get.py
src/plone/restapi/tests/http-examples/portrait_self_404_get.resp
src/plone/restapi/tests/http-examples/portrait_self_get.req
src/plone/restapi/tests/http-examples/portrait_self_get.resp
src/plone/restapi/tests/http-examples/portrait_username_get.req
src/plone/restapi/tests/http-examples/portrait_username_get.resp
src/plone/restapi/tests/http-examples/translated_messages_addons.resp
src/plone/restapi/tests/http-examples/users_update_portrait_get.resp
src/plone/restapi/tests/test_services_users.py

Fixes: #1480 and addresses https://github.com/plone/volto/pull/3487 (the /portal_memberdata/portrait traversal is not working with ++api++).
Let me know what do you think.
/cc @jmevissen

Add @portrait endpoint

---

news/1487.bugfix
src/plone/restapi/services/content/add.py
src/plone/restapi/services/content/utils.py
src/plone/restapi/tests/test_content_post.py

Validate the id in the content POST service

---

news/1488.bugfix
src/plone/restapi/services/content/add.py
src/plone/restapi/services/content/utils.py
src/plone/restapi/tests/http-examples/translated_messages_addons.resp
src/plone/restapi/tests/test_content_post.py

My fix in #1488 was too aggressive and was disallowing some ids that should be allowed; I need to take a closer look. In the meantime let's revert the change.

Revert 1488

---

news/1492.bugfix
src/plone/restapi/tests/test_auth.py
src/plone/restapi/tests/test_content_local_roles.py
src/plone/restapi/tests/test_content_post.py
src/plone/restapi/tests/test_copymove.py
src/plone/restapi/tests/test_documentation.py
src/plone/restapi/tests/test_search.py
src/plone/restapi/tests/test_services_comments.py
src/plone/restapi/tests/test_services_types.py
src/plone/restapi/tests/test_services_users.py

Intended to be merged along with https://github.com/plone/Products.PlonePAS/pull/69 (but should also be backwards compatible)

Increase length of passwords used in tests

---

news/1493.bugfix
src/plone/restapi/serializer/user.py
src/plone/restapi/tests/test_serializer_user.py
src/plone/restapi/tests/test_services_users.py

Use json_compatible when serializing users

---

.github/workflows/tests.yml
news/1515.internal

Cache buildout eggs between builds

---

docs/source/_templates/layout.html
docs/source/conf.py
news/1518.doc

Fixes https://github.com/plone/plone.restapi/issues/1447

Add Matomo Analytics, Remove Google Analytics

---

docs/source/endpoints/index.md
docs/source/endpoints/system.md
docs/source/endpoints/upgrade.md
news/1525.feature
src/plone/restapi/services/configure.zcml
src/plone/restapi/services/system/get.py
src/plone/restapi/services/upgrade/configure.zcml
src/plone/restapi/services/upgrade/get.py
src/plone/restapi/services/upgrade/post.py
src/plone/restapi/tests/http-examples/upgrade_get.req
src/plone/restapi/tests/http-examples/upgrade_get.resp
src/plone/restapi/tests/http-examples/upgrade_post.req
src/plone/restapi/tests/http-examples/upgrade_post.resp
src/plone/restapi/tests/http-examples/upgrade_post_dry_run.req
src/plone/restapi/tests/http-examples/upgrade_post_dry_run.resp
src/plone/restapi/tests/test_services_upgrade.py
src/plone/restapi/tests/test_system.py

Add @upgrade service

---

news/1536.bugfix
src/plone/restapi/blocks_linkintegrity.py

Fixes https://github.com/plone/plone.restapi/issues/1536

Fix AttributeError REQUEST in linkintegrity when pasting nested content

---

docs/source/endpoints/searching.md
news/1532.bugfix
src/plone/restapi/search/query.py
src/plone/restapi/tests/http-examples/search_sort_multiple_indexes.req
src/plone/restapi/tests/http-examples/search_sort_multiple_indexes.resp
src/plone/restapi/tests/test_documentation.py

Fixes #1532 
Tests are missing... I can't find any test for the `ZCatalogCompatibleQueryAdapter`... I will try to write something.

handle sort_on and sort_order parameters to allow both lists and strings

---

README.rst
news/1555.doc

Refs https://github.com/plone/documentation/issues/1376

Update links to demo site

---

news/1567.bugfix
src/plone/restapi/tests/test_dxfield_deserializer.py

Testfix for changes in `zope.schema >= 7.0.0`

---

news/1572.bugfix
src/plone/restapi/services/auth/login.py
src/plone/restapi/tests/test_functional_auth.py

Fix auth cookie for Zope users in login endpoint

---

news/1575.bugfix
src/plone/restapi/services/registry/update.py
src/plone/restapi/tests/test_registry.py

Fix bug with registry service that would not support tuple records

---

news/1587.feature
src/plone/restapi/cache/configure.zcml
src/plone/restapi/cache/paths.py
src/plone/restapi/configure.zcml
src/plone/restapi/tests/test_cache_purge_urls.py

Implement IPurgePaths for RestAPI traversal

---

news/1590.bugfix
src/plone/restapi/deserializer/blocks.py
src/plone/restapi/deserializer/configure.zcml
src/plone/restapi/serializer/blocks.py
src/plone/restapi/serializer/configure.zcml
src/plone/restapi/tests/test_blocks_deserializer.py
src/plone/restapi/tests/test_blocks_serializer.py

Fixes https://github.com/plone/plone.restapi/issues/1590
@pbauer

add slateTable serializers / deserializers

---

docs/source/conf.py
news/1596.documentation

Just for completeness. Not used yet.

Update intersphinx_mapping for training

---

news/1600.bugfix
src/plone/restapi/deserializer/relationfield.py
src/plone/restapi/tests/test_dxfield_deserializer.py

Fix UnboundLocalError in RelationChoice deserializer

---

news/1628.bugfix
src/plone/restapi/services/querystringsearch/get.py
src/plone/restapi/tests/test_services_querystringsearch.py

- unset the GET Paramter in Service QuerystringSearchGet
- rename test_querystringsearch_metadata_fields to test_querystringsearch_metadata_fields_post
- add test_querystringsearch_metadata_fields_get

Fix for #1628

---

news/1653.bugfix
src/plone/restapi/services/querystringsearch/get.py
src/plone/restapi/tests/test_services_querystringsearch.py

Fix validation of querystring-search input

---

.github/workflows/black.yml
.github/workflows/flake8.yml
.github/workflows/pyroma.yml
.github/workflows/tests.yml
.github/workflows/update_remote_docs.yml
.github/workflows/zpretty.yml
news/1656.internal
news/1659.internal

This pr aims to allow tests to run on PRs from forks
- putting `pull_request` in on in all `.yml` files here:
- ` if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name` in all jobs.
This pr is reated to isse #1656

Allow PRs from forks to run tests

---

docs/source/usage/content.md

Remove traces of Archetypes.

---

news/1673.bugfix
src/plone/restapi/services/relations/add.py
src/plone/restapi/services/relations/get.py

https://github.com/plone/plone.restapi/pull/1673/files#diff-824cf6a236d08b47dbcc8aff965d2e0cf5fc6748f566041aa2d4b6c00b260454R213

Fix broken relations info

---

docs/source/endpoints/users.md
news/1692.documentation

Formatting, MyST, grammar fixes.

Documentation fixes for #1599

---

docs/source/upgrade-guide.md
news/1698.documentation

This PR adds some MyST syntax for inline literals.

Polish docs for v9 release.

---

news/1651.bugfix
src/plone/restapi/serializer/dxcontent.py
src/plone/restapi/tests/test_services_history.py

Skip next/previous info for old versions if it can't be obtained (#1651)

---

news/1703.internal
src/plone/restapi/services/navigation/get.py

Remove unused code

---

.github/workflows/tests.yml
news/1740.internal

https://github.com/python/cpython/issues/113267 has been fixed.
Fixes #1740

Use last version of Python 3.12 in tests

---

news/943.bugfix
src/plone/restapi/services/users/add.py

Fix password reset when using email as login

---

news/1782.bugfix
news/1783.bugfix
setup.py

Fixes missing test req

---

news/1802.bugfix
src/plone/restapi/pas/add_plugin.zpt
src/plone/restapi/pas/config.zpt

----
📚 Documentation preview 📚: https://plonerestapi--1804.org.readthedocs.build/

fix #1802 and #1803

---

news/1830.bugfix
src/plone/restapi/serializer/site.py
src/plone/restapi/tests/dxtypes.py
src/plone/restapi/tests/test_site_serializer.py

Fixes #1830
----
📚 Documentation preview 📚: https://plonerestapi--1831.org.readthedocs.build/

Fixes Plone Site serialization when there is a field with read_permision set

---

news/1857.bugfix
src/plone/restapi/services/querystringsearch/get.py

----
📚 Documentation preview 📚: https://plonerestapi--1857.org.readthedocs.build/

Handle more BadRequests

---

.readthedocs.yaml

----
📚 Documentation preview 📚: https://plonerestapi--1870.org.readthedocs.build/

Linkcheck fixes

---

news/1888.bugfix
src/plone/restapi/services/users/add.py
src/plone/restapi/tests/test_services_users.py

----
📚 Documentation preview 📚: https://plonerestapi--1889.org.readthedocs.build/

Allow sending `sendPasswordReset` if self registration is enabled.

---

news/1895.bugfix
src/plone/restapi/services/inherit/get.py

Fixes #1895 
----
📚 Documentation preview 📚: https://plonerestapi--1896.org.readthedocs.build/

Fix context for `@inherit` endpoint serialization

---

news/1893.bugfix
src/plone/restapi/services/addons/addons.py
src/plone/restapi/services/querystringsearch/get.py
src/plone/restapi/tests/test_search.py
src/plone/restapi/tests/test_serializer_catalog.py

Fixes #1893 
----
📚 Documentation preview 📚: https://plonerestapi--1894.org.readthedocs.build/

Fix packaging imports

---

news/1897.feature
setup.py
src/plone/restapi/tests/test_services_inherit.py

Fixes #1897 
here's my contribution for the Bucharest Sprint! 🎉
----
📚 Documentation preview 📚: https://plonerestapi--1902.org.readthedocs.build/

Add tests for @inherit service endpoint 

---

news/1911.bugfix
src/plone/restapi/serializer/blocks.py
src/plone/restapi/tests/test_blocks_serializer.py

Fixes #1911 
----
📚 Documentation preview 📚: https://plonerestapi--1912.org.readthedocs.build/

Don't include teaser target data if user doesn't have permission

---

news/4097.documentation
requirements-docs.txt

See https://github.com/plone/Products.CMFPlone/issues/4097
----
📚 Documentation preview 📚: https://plonerestapi--1918.org.readthedocs.build/

Pin plone-sphinx-theme to prepare for PLIP 4097

---

news/1922.bugfix.md
src/plone/restapi/serializer/relationfield.py

Fixes #1922
----
📚 Documentation preview 📚: https://plonerestapi--1923.org.readthedocs.build/

Fix `list` used a default argument

---

Makefile
docs/source/contributing/index.md
news/+1925.documentation

----
📚 Documentation preview 📚: https://plonerestapi--1925.org.readthedocs.build/

Add install command and update contrib docs

---

docs/source/endpoints/controlpanels.md
news/1927.bugfix
src/plone/restapi/controlpanels/rules.py
src/plone/restapi/controlpanels/types.py
src/plone/restapi/deserializer/controlpanels/__init__.py
src/plone/restapi/serializer/controlpanels/__init__.py
src/plone/restapi/tests/http-examples/controlpanels_get_contentrules.resp
src/plone/restapi/tests/http-examples/controlpanels_get_dexterity.resp
src/plone/restapi/tests/test_services_controlpanels.py

Fixes #1927 
----
📚 Documentation preview 📚: https://plonerestapi--1933.org.readthedocs.build/

Remove data and schema from non-schema-based control panels

---

news/1950.bugfix
src/plone/restapi/locales/de/LC_MESSAGES/plone.restapi.po

- [x ] I signed and returned the [Plone Contributor Agreement](https://plone.org/foundation/contributors-agreement), and received and accepted an invitation to join a team in the Plone GitHub organization.
-----
If your pull request closes an open issue, include the exact text below, immediately followed by the issue number. When your pull request gets merged, then that issue will close automatically.
Closes #
----
📚 Documentation preview 📚: https://plonerestapi--1950.org.readthedocs.build/

Add some German translations
